import esbuild from "esbuild";
import process from "process";

let builtins = [];
try {
	// try dynamic import to avoid hard dependency in CI if package isn't installed
	// `builtin-modules` exports a default array of builtin Node modules
	// using import() so missing package won't throw at module load time
	// when not present in the environment.
	// eslint-disable-next-line node/no-unsupported-features/es-syntax
	const mod = await import("builtin-modules");
	builtins = mod.default || [];
} catch (e) {
	builtins = [];
}

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProd = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: isProd ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (isProd) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
