/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GenWikiPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  provider: "gemini",
  geminiApiKey: "",
  geminiModel: "gemini-3.5-flash",
  geminiBaseUrl: "https://generativelanguage.googleapis.com",
  anthropicApiKey: "",
  anthropicModel: "claude-sonnet-4-6",
  anthropicBaseUrl: "https://api.anthropic.com",
  openaiApiKey: "",
  openaiModel: "gpt-5.4-mini",
  openaiBaseUrl: "https://api.openai.com/v1",
  deepseekApiKey: "",
  deepseekModel: "deepseek-v4-flash",
  deepseekBaseUrl: "https://api.deepseek.com",
  kimiApiKey: "",
  kimiModel: "kimi-k2.6",
  kimiBaseUrl: "https://api.moonshot.cn/v1",
  openrouterApiKey: "",
  openrouterModel: "google/gemini-3.5-flash",
  openrouterBaseUrl: "https://openrouter.ai/api/v1",
  clippingsDir: "Clippings",
  wikiDir: "wiki"
};

// src/llm.ts
var import_obsidian = require("obsidian");
var LLMClient = class {
  extractString(obj, path) {
    let cur = obj;
    for (const key of path) {
      if (cur === null || cur === void 0)
        return void 0;
      if (typeof key === "number") {
        if (Array.isArray(cur))
          cur = cur[key];
        else
          return void 0;
      } else {
        if (typeof cur === "object") {
          const asObj = cur;
          cur = asObj[key];
        } else
          return void 0;
      }
    }
    return typeof cur === "string" ? cur : void 0;
  }
  constructor(settings) {
    this.settings = settings;
  }
  async complete(prompt, systemPrompt) {
    const provider = this.settings.provider;
    switch (provider) {
      case "gemini":
        return this.completeGemini(prompt, systemPrompt);
      case "anthropic":
        return this.completeAnthropic(prompt, systemPrompt);
      case "openai":
        return this.completeOpenAI(prompt, systemPrompt);
      case "deepseek":
        return this.completeDeepSeek(prompt, systemPrompt);
      case "kimi":
        return this.completeKimi(prompt, systemPrompt);
      case "openrouter":
        return this.completeOpenRouter(prompt, systemPrompt);
      default:
        throw new Error(`Unsupported LLM provider: ${provider}`);
    }
  }
  cleanUrl(baseUrl, path) {
    const cleanBase = baseUrl.trim().replace(/\/+$/, "");
    const cleanPath = path.trim().replace(/^\/+/, "");
    return `${cleanBase}/${cleanPath}`;
  }
  async completeGemini(prompt, systemPrompt) {
    const key = this.settings.geminiApiKey;
    const model = this.settings.geminiModel;
    if (!key)
      throw new Error("Gemini API key is not configured.");
    const baseUrl = this.settings.geminiBaseUrl || "https://generativelanguage.googleapis.com";
    if (baseUrl.includes("/openai")) {
      return this.completeChatCompletions(
        this.cleanUrl(baseUrl, "chat/completions"),
        key,
        model,
        prompt,
        systemPrompt
      );
    }
    const url = `${baseUrl.replace(/\/+$/, "")}/v1beta/models/${model}:generateContent?key=${key}`;
    const body = {
      contents: [{ parts: [{ text: prompt }] }]
    };
    if (systemPrompt) {
      body.systemInstruction = {
        parts: [{ text: systemPrompt }]
      };
    }
    const params = {
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(body)
    };
    const response = await (0, import_obsidian.requestUrl)(params);
    if (response.status !== 200) {
      throw new Error(`Gemini API Error (${response.status}): ${response.text}`);
    }
    const json = response.json;
    const text = this.extractString(json, ["candidates", 0, "content", "parts", 0, "text"]);
    if (!text) {
      throw new Error("Empty response received from Gemini API.");
    }
    return text;
  }
  async completeAnthropic(prompt, systemPrompt) {
    const key = this.settings.anthropicApiKey;
    const model = this.settings.anthropicModel;
    if (!key)
      throw new Error("Anthropic API key is not configured.");
    const baseUrl = this.settings.anthropicBaseUrl || "https://api.anthropic.com";
    const url = this.cleanUrl(baseUrl, "v1/messages");
    const body = {
      model,
      max_tokens: 4096,
      messages: [{ role: "user", content: prompt }]
    };
    if (systemPrompt) {
      body.system = systemPrompt;
    }
    const params = {
      url,
      method: "POST",
      headers: {
        "x-api-key": key,
        "anthropic-version": "2023-06-01",
        "Content-Type": "application/json"
      },
      body: JSON.stringify(body)
    };
    const response = await (0, import_obsidian.requestUrl)(params);
    if (response.status !== 200) {
      throw new Error(`Anthropic API Error (${response.status}): ${response.text}`);
    }
    const json = response.json;
    const text = this.extractString(json, ["content", 0, "text"]);
    if (!text) {
      throw new Error("Empty response received from Anthropic API.");
    }
    return text;
  }
  async completeOpenAI(prompt, systemPrompt) {
    const key = this.settings.openaiApiKey;
    const model = this.settings.openaiModel;
    if (!key)
      throw new Error("OpenAI API key is not configured.");
    const baseUrl = this.settings.openaiBaseUrl || "https://api.openai.com/v1";
    return this.completeChatCompletions(
      this.cleanUrl(baseUrl, "chat/completions"),
      key,
      model,
      prompt,
      systemPrompt
    );
  }
  async completeDeepSeek(prompt, systemPrompt) {
    const key = this.settings.deepseekApiKey;
    const model = this.settings.deepseekModel;
    if (!key)
      throw new Error("DeepSeek API key is not configured.");
    const baseUrl = this.settings.deepseekBaseUrl || "https://api.deepseek.com";
    if (baseUrl.trim().replace(/\/+$/, "").endsWith("/anthropic")) {
      const url = this.cleanUrl(baseUrl, "v1/messages");
      const body = {
        model,
        max_tokens: 4096,
        messages: [{ role: "user", content: prompt }]
      };
      if (systemPrompt) {
        body.system = systemPrompt;
      }
      const params = {
        url,
        method: "POST",
        headers: {
          "x-api-key": key,
          "Content-Type": "application/json"
        },
        body: JSON.stringify(body)
      };
      const response = await (0, import_obsidian.requestUrl)(params);
      if (response.status !== 200) {
        throw new Error(`DeepSeek Anthropic-compatible Error (${response.status}): ${response.text}`);
      }
      const json = response.json;
      const text = this.extractString(json, ["content", 0, "text"]);
      if (!text) {
        throw new Error("Empty response received from DeepSeek Anthropic-compatible API.");
      }
      return text;
    }
    return this.completeChatCompletions(
      this.cleanUrl(baseUrl, "chat/completions"),
      key,
      model,
      prompt,
      systemPrompt
    );
  }
  async completeKimi(prompt, systemPrompt) {
    const key = this.settings.kimiApiKey;
    const model = this.settings.kimiModel;
    if (!key)
      throw new Error("Kimi API key is not configured.");
    const baseUrl = this.settings.kimiBaseUrl || "https://api.moonshot.cn/v1";
    return this.completeChatCompletions(
      this.cleanUrl(baseUrl, "chat/completions"),
      key,
      model,
      prompt,
      systemPrompt
    );
  }
  async completeOpenRouter(prompt, systemPrompt) {
    const key = this.settings.openrouterApiKey;
    const model = this.settings.openrouterModel;
    if (!key)
      throw new Error("OpenRouter API key is not configured.");
    const baseUrl = this.settings.openrouterBaseUrl || "https://openrouter.ai/api/v1";
    return this.completeChatCompletions(
      this.cleanUrl(baseUrl, "chat/completions"),
      key,
      model,
      prompt,
      systemPrompt
    );
  }
  async completeChatCompletions(url, key, model, prompt, systemPrompt) {
    const messages = [];
    if (systemPrompt) {
      messages.push({ role: "system", content: systemPrompt });
    }
    messages.push({ role: "user", content: prompt });
    const params = {
      url,
      method: "POST",
      headers: {
        "Authorization": `Bearer ${key}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model,
        messages
      })
    };
    const response = await (0, import_obsidian.requestUrl)(params);
    if (response.status !== 200) {
      throw new Error(`API Error (${response.status}): ${response.text}`);
    }
    const json = response.json;
    const text = this.extractString(json, ["choices", 0, "message", "content"]);
    if (!text) {
      throw new Error("Empty response received from Chat Completion API.");
    }
    return text;
  }
  // Helper to extract JSON from LLM output block
  static cleanJsonString(input) {
    let clean = input.trim();
    if (clean.startsWith("```json")) {
      clean = clean.substring(7);
    } else if (clean.startsWith("```")) {
      clean = clean.substring(3);
    }
    if (clean.endsWith("```")) {
      clean = clean.substring(0, clean.length - 3);
    }
    return clean.trim();
  }
};

// src/skills.ts
function parseSkillMarkdown(content) {
  const result = {
    name: "",
    description: "",
    systemPrompt: "",
    userPromptTemplate: ""
  };
  const fmRegex = /^---\s*\n([\s\S]*?)\n---\s*\n/;
  const match = content.match(fmRegex);
  let remaining = content;
  if (match) {
    const fmContent = match[1];
    remaining = content.replace(fmRegex, "");
    const nameMatch = fmContent.match(/name:\s*(.*)/);
    const descMatch = fmContent.match(/description:\s*(.*)/);
    if (nameMatch)
      result.name = nameMatch[1].trim();
    if (descMatch)
      result.description = descMatch[1].trim();
  }
  const sysPromptIndex = remaining.indexOf("# System Prompt");
  const inputContextIndex = remaining.indexOf("# Input Context");
  if (sysPromptIndex !== -1 && inputContextIndex !== -1) {
    result.systemPrompt = remaining.substring(sysPromptIndex + 15, inputContextIndex).trim();
    result.userPromptTemplate = remaining.substring(inputContextIndex + 15).trim();
  } else if (sysPromptIndex !== -1) {
    result.systemPrompt = remaining.substring(sysPromptIndex + 15).trim();
  } else {
    result.userPromptTemplate = remaining.trim();
  }
  return result;
}
function fillTemplate(template, variables) {
  let filled = template;
  for (const [key, value] of Object.entries(variables)) {
    const placeholder = new RegExp(`{{\\s*${key}\\s*}}`, "g");
    filled = filled.replace(placeholder, value);
  }
  return filled;
}
var DEFAULT_INGEST_SKILL = `---
name: Ingest
description: Extract source clippings and merge them into the existing knowledge base.
version: 1.0.0
---

# System Prompt
You are a rigorous personal knowledge base organization expert. Your task is to read the given clipping content, extract key entities, concepts, and conclusions, and systematically merge them into the existing Wiki knowledge base directory.

Please strictly adhere to the following SOP:
1. **Merge First**: Check the "Existing Knowledge Directory" to see if highly relevant topic/entity pages exist. If so, generate a modification plan for them; if not, suggest creating a new page.
2. **Generate Wikilinks**: When new or updated content references existing entities/concepts, you must use Obsidian wikilinks (e.g., [[Entity_Name]]).
3. **Metadata**: Provide a concise one-sentence summary describing the entity or concept.
4. **Flag Contradictions**: If new information contradicts existing pages, explicitly flag it and add a warning at the top of the conflicting page.

# Input Context
## Existing Knowledge Directory
{{index_content}}

## Pending Clipping Content
{{clipping_content}}

# Output Format
You MUST return the following JSON formatted data. Do NOT include any extra markdown wrappers (like \`\`\`json):
{
  "operations": [
    {
      "action": "create", // "modify" or "create"
      "path": "wiki/Entity_Karpathy.md",
      "title": "Andrej Karpathy",
      "content": "# Andrej Karpathy\\n...Here is the updated full Markdown content..."
    }
  ],
  "index_updates": [
    {
      "path": "wiki/Entity_Karpathy.md",
      "summary": "Updated one-sentence summary..."
    }
  ],
  "contradictions": [
    {
      "page": "wiki/LLM_Wiki.md",
      "reason": "The new article points out a conflict with previously recorded content."
    }
  ]
}
`;
var DEFAULT_QUERY_SKILL = `---
name: Query
description: Conversation engine: locate answers from the index and respond.
version: 1.0.0
---

# System Prompt
You are an intelligent Wiki QA assistant. Your task is to answer the user's question based on the provided related Wiki page content.
You must ensure:
1. **Only answer based on the given page content**. If the content does not contain the answer, say "No relevant records in the knowledge base, please import new clippings."
2. **Cite Sources**: At the end of key sentences, cite the referenced Wiki page using [[Page_Name#Section]].
3. **Maintain Obsidian Formatting**: Answer in Markdown, preserving paragraph layout.

# Input Context
## User Question
{{user_question}}

## Related Wiki Content
{{page_contents}}

# Output Format
Output the Markdown response directly, appending [[Wikilinks]] at the end of sentences.
`;
var DEFAULT_SAVEPAGE_SKILL = `---
name: SavePage
description: Remove conversational tone from Q&A and refine it into a standard Wiki page.
version: 1.0.0
---

# System Prompt
You are a Wiki page refinement expert. Your task is to read the user's question and the assistant's answer, and convert it into a well-formatted, objective, and clearly structured Wiki knowledge base Markdown page.

Please follow these conversion rules:
1. **Remove Conversational Tone**: Remove all chatty or greeting phrases like "Sure, here is the answer:", "Of course, a comparison reveals...".
2. **Standardize Naming and Outline**: Use # for the main title, and ## and ### for internal semantic divisions.
3. **Preserve and Fix Wikilinks**: Keep the original [[wikilinks]] and standardize their names based on global knowledge.
4. **Generate Summary and Aliases**: Create aliases and a one-sentence summary suitable for Obsidian Frontmatter.

# Input Context
## User Question
{{user_question}}

## Original Answer Content
{{assistant_answer}}

# Output Format
Strictly return the following JSON data. Do not include any extra Markdown wrappers:
{
  "title": "PageTitle", // Recommended file title
  "frontmatter": {
    "aliases": ["Alias"],
    "summary": "One-sentence summary"
  },
  "content": "# Title\\n...Body content..."
}
`;
var DEFAULT_LINT_SKILL = `---
name: Lint
description: Knowledge health check: look for conflicts, stale information, and orphan nodes.
version: 1.0.0
---

# System Prompt
You are a knowledge base auditor. Your task is to compare the input Wiki page groups and identify the following health issues:
1. **Information Contradiction**: Different pages have conflicting descriptions for the same fact or data.
2. **Orphan Node**: The page has no inbound wikilinks and can be easily lost.
3. **Stale or Empty Page**: Content is too empty or marked as needing supplementation.

# Input Context
## Wiki Page Set for Health Check
{{group_pages}}

# Output Format
Strictly return the following JSON data. Do not include any extra wrappers or explanations:
{
  "contradictions": [
    {
      "files": ["wiki/PageA.md", "wiki/PageB.md"],
      "description": "Conflict description"
    }
  ],
  "orphans": [
    "wiki/PageC.md"
  ],
  "suggestions": [
    "Suggest adding a reference to wiki/PageC.md in wiki/PageD.md."
  ]
}
`;

// src/chat_view.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_CHAT = "genwiki-chat-view";
var GenWikiChatView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "GenWiki Chat";
  }
  getIcon() {
    return "cpu";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("genwiki-chat-view");
    const headerRow = container.createDiv({ cls: "genwiki-header-row" });
    headerRow.createEl("h3", { text: "\u{1F4AC} GenWiki Chat" });
    const startIngestBtn = headerRow.createEl("button", {
      cls: "genwiki-top-ingest-btn mod-cta",
      text: "\u{1F4E5} Process Clippings"
    });
    startIngestBtn.addEventListener("click", () => {
      void (async () => {
        startIngestBtn.disabled = true;
        startIngestBtn.setText("Processing...");
        new import_obsidian2.Notice("Scanning and organizing clippings...");
        try {
          await this.plugin.runIngest();
          new import_obsidian2.Notice("\u{1F389} Clippings processed successfully!");
        } catch (e) {
          new import_obsidian2.Notice(`Ingest failed: ${e.message}`);
          console.error(e);
        } finally {
          startIngestBtn.disabled = false;
          startIngestBtn.setText("\u{1F4E5} Process Clippings");
        }
      })();
    });
    this.historyContainer = container.createDiv({ cls: "genwiki-chat-history" });
    this.historyContainer.addEventListener("click", (e) => {
      const target = e.target;
      if (target && target.tagName === "A" && target.hasClass("internal-link")) {
        e.preventDefault();
        const href = target.getAttribute("href");
        if (href) {
          void this.plugin.app.workspace.openLinkText(href, "", true);
        }
      }
    });
    this.appendMessage("assistant", "Hello! I am your GenWiki assistant. I can answer questions based on concepts and entities in your current Wiki knowledge base. Insights generated from our Q&A can be saved as formal knowledge pages with one click.");
    const inputContainer = container.createDiv({ cls: "genwiki-chat-input-container" });
    this.inputArea = inputContainer.createEl("textarea", {
      cls: "genwiki-chat-input",
      placeholder: "Ask Wiki..."
    });
    this.sendButton = inputContainer.createEl("button", { text: "Send" });
    this.sendButton.addEventListener("click", () => {
      void this.handleSend();
    });
    this.inputArea.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.handleSend();
      }
    });
  }
  async onClose() {
  }
  appendMessage(sender, text) {
    const msgDiv = this.historyContainer.createDiv({
      cls: `genwiki-chat-message genwiki-chat-message-${sender}`
    });
    msgDiv.setText(text);
    this.historyContainer.scrollTop = this.historyContainer.scrollHeight;
    return msgDiv;
  }
  async handleSend() {
    const query = this.inputArea.value.trim();
    if (!query)
      return;
    this.appendMessage("user", query);
    this.inputArea.value = "";
    const assistantMsgDiv = this.appendMessage("assistant", "Thinking and searching...");
    this.sendButton.disabled = true;
    this.inputArea.disabled = true;
    try {
      const answer = await this.plugin.executeQuery(query);
      assistantMsgDiv.empty();
      const renderDiv = assistantMsgDiv.createDiv();
      await import_obsidian2.MarkdownRenderer.render(this.app, answer, renderDiv, "", this);
      const actionsDiv = assistantMsgDiv.createDiv({ cls: "genwiki-msg-actions" });
      const copyBtn = actionsDiv.createEl("button", {
        cls: "genwiki-copy-btn",
        text: "\u{1F4CB} Copy"
      });
      copyBtn.addEventListener("click", () => {
        navigator.clipboard.writeText(answer);
        new import_obsidian2.Notice("Copied to clipboard!");
      });
      const isNoRecord = answer.includes("No relevant records") || answer.includes("No relevant") || answer.includes("No relevantWiki");
      if (!isNoRecord) {
        const saveBtn = actionsDiv.createEl("button", {
          cls: "genwiki-save-btn mod-cta",
          text: "\u{1F4BE} Save as Wiki Page"
        });
        saveBtn.addEventListener("click", () => {
          void (async () => {
            saveBtn.disabled = true;
            saveBtn.setText("Summarizing...");
            try {
              await this.saveResponseToWiki(query, answer);
              saveBtn.setText("\u2705 Saved successfully");
            } catch (err) {
              new import_obsidian2.Notice(`Save failed: ${err.message}`);
              saveBtn.disabled = false;
              saveBtn.setText("\u{1F4BE} Save as Wiki Page");
            }
          })();
        });
      }
    } catch (err) {
      assistantMsgDiv.setText(`Error: ${err.message}`);
      console.error(err);
    } finally {
      this.sendButton.disabled = false;
      this.inputArea.disabled = false;
      this.historyContainer.scrollTop = this.historyContainer.scrollHeight;
    }
  }
  // P2: Save to Wiki orchestration
  async saveResponseToWiki(question, answer) {
    const skillFile = this.plugin.app.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(`${this.plugin.settings.wikiDir}/_skills/SavePage.md`));
    if (!(skillFile instanceof import_obsidian2.TFile)) {
      throw new Error("SavePage skill template missing.");
    }
    const skillRaw = await this.plugin.app.vault.read(skillFile);
    const skill = parseSkillMarkdown(skillRaw);
    const userPrompt = fillTemplate(skill.userPromptTemplate, {
      user_question: question,
      assistant_answer: answer
    });
    new import_obsidian2.Notice("Formatting and formalizing...");
    const response = await this.plugin.llmClient.complete(userPrompt, skill.systemPrompt);
    const cleanResponse = LLMClient.cleanJsonString(response);
    const parsed = (() => {
      try {
        return JSON.parse(cleanResponse);
      } catch (e) {
        console.error("Failed to parse SavePage response JSON", cleanResponse, e);
        throw new Error("Invalid JSON format generated by the model. Please try again.");
      }
    })();
    if (typeof parsed !== "object" || parsed === null) {
      throw new Error("The JSON generated by the model is not an object and cannot be saved.");
    }
    const result = parsed;
    const title = typeof result.title === "string" ? result.title : void 0;
    const content = typeof result.content === "string" ? result.content : void 0;
    const frontmatter = typeof result.frontmatter === "object" && result.frontmatter !== null ? result.frontmatter : void 0;
    if (!title || !content) {
      throw new Error("The saved data is missing the required title or content.");
    }
    const fileName = title.replace(/[\\/:*?"<>|]/g, "_");
    const destPath = (0, import_obsidian2.normalizePath)(`${this.plugin.settings.wikiDir}/${fileName}.md`);
    const fileExists = this.plugin.app.vault.getAbstractFileByPath(destPath);
    if (fileExists) {
      throw new Error(`File ${destPath}  already exists and cannot be overwritten. Please rename it manually in the sidebar and try again.`);
    }
    const fm = frontmatter || {};
    const aliasesRaw = fm["aliases"];
    const aliasesArr = Array.isArray(aliasesRaw) ? aliasesRaw.map((a) => String(a)) : [];
    const aliasesStr = aliasesArr.length > 0 ? JSON.stringify(aliasesArr) : "[]";
    const summaryStr = typeof fm["summary"] === "string" ? fm["summary"] : "";
    const fullContent = `---
	aliases: ${aliasesStr}
	summary: "${summaryStr.replace(/"/g, '\\"')}"
	last_updated: ${(/* @__PURE__ */ new Date()).toISOString()}
	status: active
	---

	${content}`;
    await this.plugin.app.vault.create(destPath, fullContent);
    const db = await this.plugin.loadDatabase();
    const fileHash = await this.plugin.calculateHash(fullContent);
    const linksTo = this.plugin.extractLinks(fullContent);
    db.wiki_pages[destPath] = {
      path: destPath,
      title,
      aliases: aliasesArr || [],
      type: "general",
      summary: summaryStr,
      status: "active",
      last_updated: (/* @__PURE__ */ new Date()).toISOString(),
      sha256: fileHash,
      links_to: linksTo,
      links_from: [],
      claims: [
        {
          clipping_path: "ChatInteraction",
          line_range: "all",
          paragraph_summary: summaryStr
        }
      ],
      audit: {
        created_at: (/* @__PURE__ */ new Date()).toISOString(),
        last_compiled_cost_usd: 0.01,
        history: [
          {
            timestamp: (/* @__PURE__ */ new Date()).toISOString(),
            action: "create",
            trigger: "chat_save",
            source: "ChatInteraction"
          }
        ]
      }
    };
    for (const outgoing of linksTo) {
      const targetPage = db.wiki_pages[outgoing];
      if (targetPage && !targetPage.links_from.includes(destPath)) {
        targetPage.links_from.push(destPath);
      }
    }
    await this.plugin.saveDatabase(db);
    await this.plugin.rebuildIndexMd(db);
    await this.plugin.logAction("chat_save", title);
    new import_obsidian2.Notice(`\u{1F389} Knowledge node [[${title}]] has been successfully added to the Wiki!`);
    const newFile = this.plugin.app.vault.getAbstractFileByPath(destPath);
    if (newFile instanceof import_obsidian2.TFile) {
      const leaf = this.plugin.app.workspace.getLeaf(false);
      if (leaf)
        await leaf.openFile(newFile);
    }
  }
};

// src/main.ts
var GenWikiPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.llmClient = new LLMClient(this.settings);
    this.registerView(
      VIEW_TYPE_CHAT,
      (leaf) => new GenWikiChatView(leaf, this)
    );
    await this.initFolders();
    await this.initDefaultTemplates();
    this.addSettingTab(new GenWikiSettingTab(this.app, this));
    this.addRibbonIcon("cpu", "GenWiki: Open Chat Panel", () => {
      this.activateView();
    });
    this.addCommand({
      id: "ingest-clippings",
      name: "Ingest Clippings",
      callback: async () => {
        new import_obsidian3.Notice("Starting to organize clippings...");
        try {
          await this.runIngest();
        } catch (e) {
          new import_obsidian3.Notice(`Ingest failed: ${e.message}`);
          console.error(e);
        }
      }
    });
    this.addCommand({
      id: "query-wiki",
      name: "Query Wiki",
      callback: () => {
        new QueryModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "lint-wiki",
      name: "Lint Wiki (Health Check)",
      callback: async () => {
        new import_obsidian3.Notice("Starting knowledge base health audit...");
        try {
          await this.runLint();
        } catch (e) {
          new import_obsidian3.Notice(`Lint failed: ${e.message}`);
          console.error(e);
        }
      }
    });
    this.addCommand({
      id: "open-chat-view",
      name: "Open Chat Panel",
      callback: () => this.activateView()
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.llmClient = new LLMClient(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CHAT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  // Helper to calculate SHA256 in a pure client environment, with mobile fallback
  async calculateHash(text) {
    if (typeof crypto !== "undefined" && crypto.subtle) {
      const msgBuffer = new TextEncoder().encode(text);
      const hashBuffer = await crypto.subtle.digest("SHA-256", msgBuffer);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
    } else {
      let hash = 0;
      for (let i = 0; i < text.length; i++) {
        const char = text.charCodeAt(i);
        hash = (hash << 5) - hash + char;
        hash = hash & hash;
      }
      return Math.abs(hash).toString(16).padStart(8, "0");
    }
  }
  async initFolders() {
    const folders = [
      this.settings.clippingsDir,
      `${this.settings.clippingsDir}/Archived`,
      this.settings.wikiDir,
      `${this.settings.wikiDir}/_skills`,
      `${this.settings.wikiDir}/_agents`,
      `${this.settings.wikiDir}/_database`
    ];
    for (const folder of folders) {
      const normalized = (0, import_obsidian3.normalizePath)(folder);
      const exists = this.app.vault.getAbstractFileByPath(normalized);
      if (!exists) {
        await this.app.vault.createFolder(normalized);
      }
    }
  }
  async initDefaultTemplates() {
    const templates = [
      { path: `${this.settings.wikiDir}/_skills/Ingest.md`, content: DEFAULT_INGEST_SKILL },
      { path: `${this.settings.wikiDir}/_skills/Query.md`, content: DEFAULT_QUERY_SKILL },
      { path: `${this.settings.wikiDir}/_skills/SavePage.md`, content: DEFAULT_SAVEPAGE_SKILL },
      { path: `${this.settings.wikiDir}/_skills/Lint.md`, content: DEFAULT_LINT_SKILL }
    ];
    for (const t of templates) {
      const normalized = (0, import_obsidian3.normalizePath)(t.path);
      const file2 = this.app.vault.getAbstractFileByPath(normalized);
      if (!file2) {
        await this.app.vault.create(normalized, t.content);
      }
    }
    const claudePath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_agents/CLAUDE.md`);
    const file = this.app.vault.getAbstractFileByPath(claudePath);
    if (!file) {
      await this.app.vault.create(claudePath, `# CLAUDE.md

This protocol governs how GenWiki processes knowledge.`);
    }
    const indexPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/index.md`);
    if (!this.app.vault.getAbstractFileByPath(indexPath)) {
      await this.app.vault.create(indexPath, `# Knowledge Index

This file is an auto-generated index.`);
    }
    const logPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/log.md`);
    if (!this.app.vault.getAbstractFileByPath(logPath)) {
      await this.app.vault.create(logPath, `# Action Audit Logs

Records every knowledge organization and query action.`);
    }
  }
  async loadDatabase() {
    const dbPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_database/index.json`);
    const file = this.app.vault.getAbstractFileByPath(dbPath);
    if (file instanceof import_obsidian3.TFile) {
      const text = await this.app.vault.read(file);
      try {
        const parsed = JSON.parse(text);
        if (typeof parsed === "object" && parsed !== null && "wiki_pages" in parsed) {
          return parsed;
        }
        console.error("Database file has unexpected shape, resetting");
      } catch (e) {
        console.error("Failed to parse database file, resetting", e);
      }
    }
    return {
      version: "1.0.0",
      last_indexed: (/* @__PURE__ */ new Date()).toISOString(),
      clippings: {},
      wiki_pages: {}
    };
  }
  async saveDatabase(db) {
    const dbPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_database/index.json`);
    const file = this.app.vault.getAbstractFileByPath(dbPath);
    const content = JSON.stringify(db, null, 2);
    if (file instanceof import_obsidian3.TFile) {
      await this.app.vault.modify(file, content);
    } else {
      await this.app.vault.create(dbPath, content);
    }
  }
  async logAction(action, title) {
    const logPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/log.md`);
    const file = this.app.vault.getAbstractFileByPath(logPath);
    if (file instanceof import_obsidian3.TFile) {
      const dateStr = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
      const entry = `
## [${dateStr}] ${action} | ${title}
`;
      await this.app.vault.append(file, entry);
    }
  }
  // Extract outgoing double links from text
  extractLinks(text) {
    const links = [];
    const regex = /\[\[(.*?)\]\]/g;
    let match;
    while ((match = regex.exec(text)) !== null) {
      let link = match[1];
      if (link.includes("|")) {
        link = link.split("|")[0];
      }
      if (link.includes("#")) {
        link = link.split("#")[0];
      }
      const normalizedLink = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/${link.trim()}.md`);
      if (!links.includes(normalizedLink)) {
        links.push(normalizedLink);
      }
    }
    return links;
  }
  // Regenerate the main index.md file based on database contents
  async rebuildIndexMd(db) {
    const indexPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/index.md`);
    const file = this.app.vault.getAbstractFileByPath(indexPath);
    if (!(file instanceof import_obsidian3.TFile))
      return;
    let content = `# Knowledge Index

This page is auto-updated by GenWiki, showing an index graph of all archived knowledge points.

## Concepts
`;
    const concepts = Object.values(db.wiki_pages).filter((p) => p.type === "concept" && p.status !== "archived");
    const entities = Object.values(db.wiki_pages).filter((p) => p.type === "entity" && p.status !== "archived");
    const generals = Object.values(db.wiki_pages).filter((p) => p.type === "general" && p.status !== "archived");
    for (const p of concepts) {
      content += `* [[${p.title}]] - *${p.summary}*
`;
    }
    content += `
## Entities
`;
    for (const p of entities) {
      content += `* [[${p.title}]] - *${p.summary}*
`;
    }
    content += `
## General Pages
`;
    for (const p of generals) {
      content += `* [[${p.title}]] - *${p.summary}*
`;
    }
    await this.app.vault.modify(file, content);
  }
  // P1: Ingest Process
  async runIngest() {
    const clippingsFolder = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(this.settings.clippingsDir));
    if (!(clippingsFolder instanceof import_obsidian3.TFolder)) {
      throw new Error(`Clippings directory ${this.settings.clippingsDir} does not exist.`);
    }
    const db = await this.loadDatabase();
    const files = clippingsFolder.children;
    const mdFiles = files.filter((f) => f instanceof import_obsidian3.TFile && f.extension === "md");
    let processedAny = false;
    for (const mdFile of mdFiles) {
      const relativePath = mdFile.path;
      if (relativePath.includes("/Archived/"))
        continue;
      const clippingMeta = db.clippings[relativePath];
      if (clippingMeta && clippingMeta.status === "processed")
        continue;
      const content = await this.app.vault.read(mdFile);
      const hash = await this.calculateHash(content);
      const indexFile = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/index.md`));
      const indexContent = indexFile instanceof import_obsidian3.TFile ? await this.app.vault.read(indexFile) : "";
      const skillFile = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_skills/Ingest.md`));
      if (!(skillFile instanceof import_obsidian3.TFile)) {
        throw new Error("Ingest skill template missing.");
      }
      const skillRaw = await this.app.vault.read(skillFile);
      const skill = parseSkillMarkdown(skillRaw);
      const userPrompt = fillTemplate(skill.userPromptTemplate, {
        index_content: indexContent,
        clipping_content: content
      });
      new import_obsidian3.Notice(`Analyzing with AI: ${mdFile.name}...`);
      const response = await this.llmClient.complete(userPrompt, skill.systemPrompt);
      const cleanResponse = LLMClient.cleanJsonString(response);
      let resultParsed;
      try {
        resultParsed = JSON.parse(cleanResponse);
      } catch (e) {
        console.error("Failed to parse LLM Response JSON", cleanResponse, e);
        new import_obsidian3.Notice(`Invalid JSON returned by the model. Please try again!`);
        db.clippings[relativePath] = {
          path: relativePath,
          sha256: hash,
          ingest_date: (/* @__PURE__ */ new Date()).toISOString(),
          status: "failed",
          destinations: []
        };
        await this.saveDatabase(db);
        continue;
      }
      if (typeof resultParsed !== "object" || resultParsed === null) {
        new import_obsidian3.Notice(`Invalid JSON format (not an object) returned by the model, please try again!`);
        db.clippings[relativePath] = {
          path: relativePath,
          sha256: hash,
          ingest_date: (/* @__PURE__ */ new Date()).toISOString(),
          status: "failed",
          destinations: []
        };
        await this.saveDatabase(db);
        continue;
      }
      const result = resultParsed;
      const destinations = [];
      const operations = Array.isArray(result.operations) ? result.operations : [];
      for (const opRaw of operations) {
        if (typeof opRaw !== "object" || opRaw === null)
          continue;
        const op = opRaw;
        const action = typeof op.action === "string" ? op.action : "unknown";
        const opPath = typeof op.path === "string" ? op.path : void 0;
        const opContent = typeof op.content === "string" ? op.content : void 0;
        const opTitle = typeof op.title === "string" ? op.title : void 0;
        if (!opPath)
          continue;
        const destPath = (0, import_obsidian3.normalizePath)(opPath);
        destinations.push(destPath);
        const opFile = this.app.vault.getAbstractFileByPath(destPath);
        if (action === "create" || !opFile) {
          const parts = destPath.split("/");
          if (parts.length > 1) {
            const parentDir = parts.slice(0, parts.length - 1).join("/");
            if (!this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(parentDir))) {
              await this.app.vault.createFolder((0, import_obsidian3.normalizePath)(parentDir));
            }
          }
          await this.app.vault.create(destPath, opContent || "");
        } else if (opFile instanceof import_obsidian3.TFile) {
          await this.app.vault.modify(opFile, opContent || "");
        }
        const fileContent = opContent || "";
        const fileHash = await this.calculateHash(fileContent);
        const linksTo = this.extractLinks(fileContent);
        const indexUpdates = Array.isArray(result.index_updates) ? result.index_updates : [];
        const idxUpdateRaw = indexUpdates.find((iu) => typeof iu === "object" && iu !== null && iu.path === opPath);
        const idxUpdate = typeof idxUpdateRaw === "object" && idxUpdateRaw !== null ? idxUpdateRaw : {};
        const existingPage = db.wiki_pages[destPath];
        const auditHistory = existingPage?.audit.history || [];
        auditHistory.push({
          timestamp: (/* @__PURE__ */ new Date()).toISOString(),
          action,
          trigger: "ingest",
          source: relativePath
        });
        const idxAliasesRaw = idxUpdate["aliases"];
        const idxAliases = Array.isArray(idxAliasesRaw) ? idxAliasesRaw.map((a) => String(a)) : existingPage?.aliases || [];
        const idxTypeRaw = typeof idxUpdate["type"] === "string" ? idxUpdate["type"] : existingPage?.type;
        const idxType = idxTypeRaw === "concept" || idxTypeRaw === "entity" || idxTypeRaw === "general" ? idxTypeRaw : "general";
        const idxSummary = typeof idxUpdate["summary"] === "string" ? idxUpdate["summary"] : existingPage?.summary || "Auto-generated information entry.";
        db.wiki_pages[destPath] = {
          path: destPath,
          title: opTitle || (opFile instanceof import_obsidian3.TFile ? opFile.name.replace(".md", "") : "Untitled"),
          aliases: idxAliases,
          type: idxType,
          summary: idxSummary,
          status: "active",
          last_updated: (/* @__PURE__ */ new Date()).toISOString(),
          sha256: fileHash,
          links_to: linksTo,
          links_from: existingPage?.links_from || [],
          claims: [
            {
              clipping_path: relativePath,
              line_range: "all",
              paragraph_summary: idxSummary || "Summary from clippings"
            }
          ],
          audit: {
            created_at: existingPage?.audit.created_at || (/* @__PURE__ */ new Date()).toISOString(),
            last_compiled_cost_usd: 0.01,
            history: auditHistory
          }
        };
      }
      for (const pagePath of destinations) {
        const page = db.wiki_pages[pagePath];
        if (page) {
          for (const outgoing of page.links_to) {
            const targetPage = db.wiki_pages[outgoing];
            if (targetPage && !targetPage.links_from.includes(pagePath)) {
              targetPage.links_from.push(pagePath);
            }
          }
        }
      }
      db.clippings[relativePath] = {
        path: relativePath,
        sha256: hash,
        ingest_date: (/* @__PURE__ */ new Date()).toISOString(),
        status: "processed",
        destinations
      };
      await this.logAction("ingest", mdFile.name);
      const archivedPath = (0, import_obsidian3.normalizePath)(`${this.settings.clippingsDir}/Archived/${mdFile.name}`);
      await this.app.vault.rename(mdFile, archivedPath);
      processedAny = true;
    }
    if (processedAny) {
      await this.saveDatabase(db);
      await this.rebuildIndexMd(db);
      new import_obsidian3.Notice("\u{1F389} Clippings merged and indexed successfully!");
    } else {
      new import_obsidian3.Notice("No unprocessed clippings found!");
    }
  }
  // P1: Query core execution
  async executeQuery(question) {
    const db = await this.loadDatabase();
    const querySkillFile = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_skills/Query.md`));
    if (!(querySkillFile instanceof import_obsidian3.TFile)) {
      throw new Error("Query skill template missing.");
    }
    const skillRaw = await this.app.vault.read(querySkillFile);
    const skill = parseSkillMarkdown(skillRaw);
    const keywords = question.toLowerCase().split(/\s+/);
    const matchingPages = [];
    for (const page of Object.values(db.wiki_pages)) {
      const matches = keywords.some(
        (kw) => page.title.toLowerCase().includes(kw) || page.summary.toLowerCase().includes(kw) || page.aliases.some((alias) => alias.toLowerCase().includes(kw))
      );
      if (matches) {
        matchingPages.push(page);
      }
    }
    const pagesToRead = matchingPages.length > 0 ? matchingPages.slice(0, 5) : Object.values(db.wiki_pages).slice(0, 5);
    let combinedContents = "";
    for (const p of pagesToRead) {
      const file = this.app.vault.getAbstractFileByPath(p.path);
      if (file instanceof import_obsidian3.TFile) {
        const content = await this.app.vault.read(file);
        combinedContents += `
=== FILE: ${p.path} ===
${content}
`;
      }
    }
    if (!combinedContents.trim()) {
      combinedContents = "(No relevant Wiki knowledge content, please ingest clippings first)";
    }
    const userPrompt = fillTemplate(skill.userPromptTemplate, {
      user_question: question,
      page_contents: combinedContents
    });
    const response = await this.llmClient.complete(userPrompt, skill.systemPrompt);
    await this.logAction("query", question);
    return response;
  }
  // P1: Lint Process
  async runLint() {
    const db = await this.loadDatabase();
    const activePages = Object.values(db.wiki_pages).filter((p) => p.status !== "archived");
    if (activePages.length === 0) {
      new import_obsidian3.Notice("There are no pages in the Wiki. Please run Ingest first!");
      return;
    }
    const lintSkillFile = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_skills/Lint.md`));
    if (!(lintSkillFile instanceof import_obsidian3.TFile)) {
      throw new Error("Lint skill template missing.");
    }
    const skillRaw = await this.app.vault.read(lintSkillFile);
    const skill = parseSkillMarkdown(skillRaw);
    const batchSize = 5;
    const contradictions = [];
    const orphans = [];
    const suggestions = [];
    for (let i = 0; i < activePages.length; i += batchSize) {
      const batch = activePages.slice(i, i + batchSize);
      let groupPagesContent = "";
      for (const page of batch) {
        const file = this.app.vault.getAbstractFileByPath(page.path);
        if (file instanceof import_obsidian3.TFile) {
          const content = await this.app.vault.read(file);
          groupPagesContent += `
=== FILE: ${page.path} ===
${content}
`;
        }
      }
      const userPrompt = fillTemplate(skill.userPromptTemplate, {
        group_pages: groupPagesContent
      });
      new import_obsidian3.Notice(`Auditing batch ${Math.floor(i / batchSize) + 1} of knowledge nodes...`);
      const response = await this.llmClient.complete(userPrompt, skill.systemPrompt);
      const cleanResponse = LLMClient.cleanJsonString(response);
      try {
        const parsed = JSON.parse(cleanResponse);
        if (typeof parsed === "object" && parsed !== null) {
          const resObj = parsed;
          if (Array.isArray(resObj.contradictions)) {
            const validContradictions = resObj.contradictions.filter((item) => typeof item === "object" && item !== null);
            contradictions.push(...validContradictions);
          }
          if (Array.isArray(resObj.orphans)) {
            const validOrphans = resObj.orphans.filter((item) => typeof item === "string").map(String);
            orphans.push(...validOrphans);
          }
          if (Array.isArray(resObj.suggestions)) {
            const validSuggestions = resObj.suggestions.filter((item) => typeof item === "string").map(String);
            suggestions.push(...validSuggestions);
          }
        }
      } catch (e) {
        console.error("Failed to parse Lint Response JSON", cleanResponse, e);
      }
    }
    const finalOrphans = orphans.filter((path) => {
      const page = db.wiki_pages[path];
      return !page || !Array.isArray(page.links_from) || page.links_from.length === 0;
    });
    const reportPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/Lint_Report.md`);
    let reportContent = `# GenWiki Knowledge Base Health Audit Report

Report generation time: ${(/* @__PURE__ */ new Date()).toLocaleString()}

`;
    reportContent += `## 1. Information Conflicts and Contradictions
`;
    if (contradictions.length > 0) {
      for (const cRaw of contradictions) {
        if (typeof cRaw !== "object" || cRaw === null)
          continue;
        const c = cRaw;
        const filesRaw = c["files"];
        const filesArr = Array.isArray(filesRaw) ? filesRaw.map((f) => String(f)) : [];
        const desc = typeof c["description"] === "string" ? c["description"] : "";
        reportContent += `* **Files involved**: ${filesArr.map((f) => `[[${f.replace(this.settings.wikiDir + "/", "").replace(".md", "")}]]`).join(", ")}
  * **Conflict description**: ${desc}
`;
      }
    } else {
      reportContent += `\u2705 No obvious logical conflicts or data contradictions detected.
`;
    }
    reportContent += `
## 2. Orphan Pages List
`;
    if (finalOrphans.length > 0) {
      for (const path of finalOrphans) {
        const title = path.replace(this.settings.wikiDir + "/", "").replace(".md", "");
        reportContent += `* [[${title}]] - *No inbound references*
`;
      }
    } else {
      reportContent += `\u2705 All Wiki pages have inbound links.
`;
    }
    reportContent += `
## 3. Association Building and Completion Suggestions
`;
    if (suggestions.length > 0) {
      for (const s of suggestions) {
        reportContent += `* ${s}
`;
      }
    } else {
      reportContent += `\u2705 The connection graph is currently complete and healthy.
`;
    }
    const reportFile = this.app.vault.getAbstractFileByPath(reportPath);
    if (reportFile instanceof import_obsidian3.TFile) {
      await this.app.vault.modify(reportFile, reportContent);
    } else {
      await this.app.vault.create(reportPath, reportContent);
    }
    await this.logAction("lint", "Lint Health Audit Report");
    new import_obsidian3.Notice("\u{1F389} Knowledge health check complete! Report generated.");
    const leaf = this.app.workspace.getLeaf(false);
    const reportFileObj = this.app.vault.getAbstractFileByPath(reportPath);
    if (leaf && reportFileObj instanceof import_obsidian3.TFile)
      await leaf.openFile(reportFileObj);
  }
};
var QueryModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F50D} Smart Wiki QA Search" });
    const inputEl = contentEl.createEl("input", {
      type: "text",
      placeholder: "Please enter your question about the Wiki (supports fuzzy semantic search)..."
    });
    inputEl.addClass("genwiki-query-input");
    const submitBtn = contentEl.createEl("button", { text: "Submit Question" });
    const resultContainer = contentEl.createDiv({ cls: "genwiki-query-result" });
    submitBtn.addEventListener("click", async () => {
      const query = inputEl.value.trim();
      if (!query)
        return;
      resultContainer.setText("Analyzing and searching, please wait...");
      submitBtn.disabled = true;
      try {
        const ans = await this.plugin.executeQuery(query);
        resultContainer.empty();
        const preEl = resultContainer.createEl("pre", { cls: "genwiki-query-pre" });
        preEl.setText(ans);
      } catch (e) {
        resultContainer.setText(`Query Error: ${e.message}`);
        console.error(e);
      } finally {
        submitBtn.disabled = false;
      }
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var GenWikiSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  addModelSetting(containerEl, providerName, presetsModel, currentModel, onModelChange) {
    const isPreset = presetsModel.includes(currentModel);
    const dropdownValue = isPreset ? currentModel : "customized";
    new import_obsidian3.Setting(containerEl).setName(`${providerName} Model`).setDesc("Select a preset model or customize").addDropdown((dropdown) => {
      for (const m of presetsModel) {
        dropdown.addOption(m, m);
      }
      dropdown.addOption("customized", "Custom");
      dropdown.setValue(dropdownValue);
      dropdown.onChange(async (val) => {
        if (val === "customized") {
          await onModelChange("");
        } else {
          await onModelChange(val);
        }
        this.display();
      });
    });
    if (dropdownValue === "customized") {
      new import_obsidian3.Setting(containerEl).setName(`Custom ${providerName} Model ID`).setDesc("Enter your custom model identifier").addText(
        (text) => text.setPlaceholder("e.g., gpt-4-custom").setValue(currentModel).onChange(async (val) => {
          await onModelChange(val);
        })
      );
    }
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Model Settings").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Default Model Provider").setDesc("Select the model provider to use").addDropdown((dropdown) => dropdown.addOption("gemini", "Google Gemini").addOption("anthropic", "Anthropic Claude").addOption("openai", "OpenAI").addOption("deepseek", "DeepSeek").addOption("kimi", "Moonshot Kimi").addOption("openrouter", "OpenRouter").setValue(this.plugin.settings.provider).onChange(async (value) => {
      this.plugin.settings.provider = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    const prov = this.plugin.settings.provider;
    if (prov === "gemini") {
      new import_obsidian3.Setting(containerEl).setName("Gemini API Key").addText((text) => text.setPlaceholder("Enter Gemini API Key").setValue(this.plugin.settings.geminiApiKey).onChange(async (value) => {
        this.plugin.settings.geminiApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "Gemini",
        [
          "gemini-3.5-flash",
          "gemini-3.1-pro-preview",
          "gemini-3.1-flash-lite",
          "gemini-2.5-pro",
          "gemini-2.5-flash",
          "gemini-2.5-flash-lite",
          "gemini-flash-latest"
        ],
        this.plugin.settings.geminiModel,
        async (val) => {
          this.plugin.settings.geminiModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "anthropic") {
      new import_obsidian3.Setting(containerEl).setName("Anthropic API Key").addText((text) => text.setPlaceholder("Enter Anthropic API Key").setValue(this.plugin.settings.anthropicApiKey).onChange(async (value) => {
        this.plugin.settings.anthropicApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "Anthropic",
        [
          "claude-opus-4-8",
          "claude-sonnet-4-6",
          "claude-haiku-4-5",
          "claude-haiku-4-5-20251001"
        ],
        this.plugin.settings.anthropicModel,
        async (val) => {
          this.plugin.settings.anthropicModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "openai") {
      new import_obsidian3.Setting(containerEl).setName("OpenAI API Key").addText((text) => text.setPlaceholder("Enter OpenAI API Key").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
        this.plugin.settings.openaiApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "OpenAI",
        [
          "gpt-5.5",
          "gpt-5.5-pro",
          "gpt-5.4",
          "gpt-5.4-mini",
          "gpt-5.4-nano",
          "chat-latest"
        ],
        this.plugin.settings.openaiModel,
        async (val) => {
          this.plugin.settings.openaiModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "deepseek") {
      new import_obsidian3.Setting(containerEl).setName("DeepSeek API Key").addText((text) => text.setPlaceholder("Enter DeepSeek API Key").setValue(this.plugin.settings.deepseekApiKey).onChange(async (value) => {
        this.plugin.settings.deepseekApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "DeepSeek",
        [
          "deepseek-v4-pro",
          "deepseek-v4-flash",
          "deepseek-chat",
          "deepseek-reasoner"
        ],
        this.plugin.settings.deepseekModel,
        async (val) => {
          this.plugin.settings.deepseekModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "kimi") {
      new import_obsidian3.Setting(containerEl).setName("Kimi API Key").addText((text) => text.setPlaceholder("Enter Moonshot API Key").setValue(this.plugin.settings.kimiApiKey).onChange(async (value) => {
        this.plugin.settings.kimiApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "Kimi",
        [
          "kimi-k2.6",
          "kimi-k2.5",
          "moonshot-v1-8k",
          "moonshot-v1-32k",
          "moonshot-v1-128k",
          "moonshot-v1-8k-vision-preview",
          "moonshot-v1-32k-vision-preview",
          "moonshot-v1-128k-vision-preview"
        ],
        this.plugin.settings.kimiModel,
        async (val) => {
          this.plugin.settings.kimiModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "openrouter") {
      new import_obsidian3.Setting(containerEl).setName("OpenRouter API Key").addText((text) => text.setPlaceholder("Enter OpenRouter API Key").setValue(this.plugin.settings.openrouterApiKey).onChange(async (value) => {
        this.plugin.settings.openrouterApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "OpenRouter",
        [
          "openai/gpt-5.5",
          "openai/gpt-5.5-pro",
          "openai/gpt-chat-latest",
          "anthropic/claude-opus-4.8",
          "anthropic/claude-sonnet-4.6",
          "anthropic/claude-sonnet-4.5",
          "google/gemini-3.5-flash",
          "google/gemini-3.1-flash-lite",
          "google/gemini-3.1-pro-preview",
          "deepseek/deepseek-v4-pro",
          "deepseek/deepseek-v4-flash",
          "moonshotai/kimi-k2.6",
          "moonshotai/kimi-k2.6:free",
          "qwen/qwen3.7-max",
          "qwen/qwen3.7-plus",
          "x-ai/grok-4.3",
          "mistralai/mistral-medium-3-5",
          "openrouter/free"
        ],
        this.plugin.settings.openrouterModel,
        async (val) => {
          this.plugin.settings.openrouterModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    new import_obsidian3.Setting(containerEl).setName("Directory Paths").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Clippings Directory").setDesc("Path for storing web clippings").addText((text) => text.setValue(this.plugin.settings.clippingsDir).onChange(async (value) => {
      this.plugin.settings.clippingsDir = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Wiki Directory").setDesc("Path for structured knowledge files").addText((text) => text.setValue(this.plugin.settings.wikiDir).onChange(async (value) => {
      this.plugin.settings.wikiDir = value;
      await this.plugin.saveSettings();
    }));
  }
  getSettingDefinitions() {
    return [];
  }
};
