/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GenWikiPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  provider: "gemini",
  geminiApiKey: "",
  geminiModel: "gemini-3.5-flash",
  geminiBaseUrl: "https://generativelanguage.googleapis.com",
  anthropicApiKey: "",
  anthropicModel: "claude-sonnet-4-6",
  anthropicBaseUrl: "https://api.anthropic.com",
  openaiApiKey: "",
  openaiModel: "gpt-5.4-mini",
  openaiBaseUrl: "https://api.openai.com/v1",
  deepseekApiKey: "",
  deepseekModel: "deepseek-v4-flash",
  deepseekBaseUrl: "https://api.deepseek.com",
  kimiApiKey: "",
  kimiModel: "kimi-k2.6",
  kimiBaseUrl: "https://api.moonshot.cn/v1",
  openrouterApiKey: "",
  openrouterModel: "google/gemini-3.5-flash",
  openrouterBaseUrl: "https://openrouter.ai/api/v1",
  clippingsDir: "Clippings",
  wikiDir: "wiki"
};

// src/llm.ts
var import_obsidian = require("obsidian");
var LLMClient = class {
  extractString(obj, path) {
    let cur = obj;
    for (const key of path) {
      if (cur === null || cur === void 0)
        return void 0;
      if (typeof key === "number") {
        if (Array.isArray(cur))
          cur = cur[key];
        else
          return void 0;
      } else {
        if (typeof cur === "object") {
          const asObj = cur;
          cur = asObj[key];
        } else
          return void 0;
      }
    }
    return typeof cur === "string" ? cur : void 0;
  }
  constructor(settings) {
    this.settings = settings;
  }
  async complete(prompt, systemPrompt) {
    const provider = this.settings.provider;
    switch (provider) {
      case "gemini":
        return this.completeGemini(prompt, systemPrompt);
      case "anthropic":
        return this.completeAnthropic(prompt, systemPrompt);
      case "openai":
        return this.completeOpenAI(prompt, systemPrompt);
      case "deepseek":
        return this.completeDeepSeek(prompt, systemPrompt);
      case "kimi":
        return this.completeKimi(prompt, systemPrompt);
      case "openrouter":
        return this.completeOpenRouter(prompt, systemPrompt);
      default:
        throw new Error(`Unsupported LLM provider: ${provider}`);
    }
  }
  cleanUrl(baseUrl, path) {
    const cleanBase = baseUrl.trim().replace(/\/+$/, "");
    const cleanPath = path.trim().replace(/^\/+/, "");
    return `${cleanBase}/${cleanPath}`;
  }
  async completeGemini(prompt, systemPrompt) {
    const key = this.settings.geminiApiKey;
    const model = this.settings.geminiModel;
    if (!key)
      throw new Error("Gemini API key is not configured.");
    const baseUrl = this.settings.geminiBaseUrl || "https://generativelanguage.googleapis.com";
    if (baseUrl.includes("/openai")) {
      return this.completeChatCompletions(
        this.cleanUrl(baseUrl, "chat/completions"),
        key,
        model,
        prompt,
        systemPrompt
      );
    }
    const url = `${baseUrl.replace(/\/+$/, "")}/v1beta/models/${model}:generateContent?key=${key}`;
    const body = {
      contents: [{ parts: [{ text: prompt }] }]
    };
    if (systemPrompt) {
      body.systemInstruction = {
        parts: [{ text: systemPrompt }]
      };
    }
    const params = {
      url,
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify(body)
    };
    const response = await (0, import_obsidian.requestUrl)(params);
    if (response.status !== 200) {
      throw new Error(`Gemini API Error (${response.status}): ${response.text}`);
    }
    const json = response.json;
    const text = this.extractString(json, ["candidates", 0, "content", "parts", 0, "text"]);
    if (!text) {
      throw new Error("Empty response received from Gemini API.");
    }
    return text;
  }
  async completeAnthropic(prompt, systemPrompt) {
    const key = this.settings.anthropicApiKey;
    const model = this.settings.anthropicModel;
    if (!key)
      throw new Error("Anthropic API key is not configured.");
    const baseUrl = this.settings.anthropicBaseUrl || "https://api.anthropic.com";
    const url = this.cleanUrl(baseUrl, "v1/messages");
    const body = {
      model,
      max_tokens: 4096,
      messages: [{ role: "user", content: prompt }]
    };
    if (systemPrompt) {
      body.system = systemPrompt;
    }
    const params = {
      url,
      method: "POST",
      headers: {
        "x-api-key": key,
        "anthropic-version": "2023-06-01",
        "Content-Type": "application/json"
      },
      body: JSON.stringify(body)
    };
    const response = await (0, import_obsidian.requestUrl)(params);
    if (response.status !== 200) {
      throw new Error(`Anthropic API Error (${response.status}): ${response.text}`);
    }
    const json = response.json;
    const text = this.extractString(json, ["content", 0, "text"]);
    if (!text) {
      throw new Error("Empty response received from Anthropic API.");
    }
    return text;
  }
  async completeOpenAI(prompt, systemPrompt) {
    const key = this.settings.openaiApiKey;
    const model = this.settings.openaiModel;
    if (!key)
      throw new Error("OpenAI API key is not configured.");
    const baseUrl = this.settings.openaiBaseUrl || "https://api.openai.com/v1";
    return this.completeChatCompletions(
      this.cleanUrl(baseUrl, "chat/completions"),
      key,
      model,
      prompt,
      systemPrompt
    );
  }
  async completeDeepSeek(prompt, systemPrompt) {
    const key = this.settings.deepseekApiKey;
    const model = this.settings.deepseekModel;
    if (!key)
      throw new Error("DeepSeek API key is not configured.");
    const baseUrl = this.settings.deepseekBaseUrl || "https://api.deepseek.com";
    if (baseUrl.trim().replace(/\/+$/, "").endsWith("/anthropic")) {
      const url = this.cleanUrl(baseUrl, "v1/messages");
      const body = {
        model,
        max_tokens: 4096,
        messages: [{ role: "user", content: prompt }]
      };
      if (systemPrompt) {
        body.system = systemPrompt;
      }
      const params = {
        url,
        method: "POST",
        headers: {
          "x-api-key": key,
          "Content-Type": "application/json"
        },
        body: JSON.stringify(body)
      };
      const response = await (0, import_obsidian.requestUrl)(params);
      if (response.status !== 200) {
        throw new Error(`DeepSeek Anthropic-compatible Error (${response.status}): ${response.text}`);
      }
      const json = response.json;
      const text = this.extractString(json, ["content", 0, "text"]);
      if (!text) {
        throw new Error("Empty response received from DeepSeek Anthropic-compatible API.");
      }
      return text;
    }
    return this.completeChatCompletions(
      this.cleanUrl(baseUrl, "chat/completions"),
      key,
      model,
      prompt,
      systemPrompt
    );
  }
  async completeKimi(prompt, systemPrompt) {
    const key = this.settings.kimiApiKey;
    const model = this.settings.kimiModel;
    if (!key)
      throw new Error("Kimi API key is not configured.");
    const baseUrl = this.settings.kimiBaseUrl || "https://api.moonshot.cn/v1";
    return this.completeChatCompletions(
      this.cleanUrl(baseUrl, "chat/completions"),
      key,
      model,
      prompt,
      systemPrompt
    );
  }
  async completeOpenRouter(prompt, systemPrompt) {
    const key = this.settings.openrouterApiKey;
    const model = this.settings.openrouterModel;
    if (!key)
      throw new Error("OpenRouter API key is not configured.");
    const baseUrl = this.settings.openrouterBaseUrl || "https://openrouter.ai/api/v1";
    return this.completeChatCompletions(
      this.cleanUrl(baseUrl, "chat/completions"),
      key,
      model,
      prompt,
      systemPrompt
    );
  }
  async completeChatCompletions(url, key, model, prompt, systemPrompt) {
    const messages = [];
    if (systemPrompt) {
      messages.push({ role: "system", content: systemPrompt });
    }
    messages.push({ role: "user", content: prompt });
    const params = {
      url,
      method: "POST",
      headers: {
        "Authorization": `Bearer ${key}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        model,
        messages
      })
    };
    const response = await (0, import_obsidian.requestUrl)(params);
    if (response.status !== 200) {
      throw new Error(`API Error (${response.status}): ${response.text}`);
    }
    const json = response.json;
    const text = this.extractString(json, ["choices", 0, "message", "content"]);
    if (!text) {
      throw new Error("Empty response received from Chat Completion API.");
    }
    return text;
  }
  // Helper to extract JSON from LLM output block
  static cleanJsonString(input) {
    let clean = input.trim();
    if (clean.startsWith("```json")) {
      clean = clean.substring(7);
    } else if (clean.startsWith("```")) {
      clean = clean.substring(3);
    }
    if (clean.endsWith("```")) {
      clean = clean.substring(0, clean.length - 3);
    }
    return clean.trim();
  }
};

// src/skills.ts
function parseSkillMarkdown(content) {
  const result = {
    name: "",
    description: "",
    systemPrompt: "",
    userPromptTemplate: ""
  };
  const fmRegex = /^---\s*\n([\s\S]*?)\n---\s*\n/;
  const match = content.match(fmRegex);
  let remaining = content;
  if (match) {
    const fmContent = match[1];
    remaining = content.replace(fmRegex, "");
    const nameMatch = fmContent.match(/name:\s*(.*)/);
    const descMatch = fmContent.match(/description:\s*(.*)/);
    if (nameMatch)
      result.name = nameMatch[1].trim();
    if (descMatch)
      result.description = descMatch[1].trim();
  }
  const sysPromptIndex = remaining.indexOf("# System Prompt");
  const inputContextIndex = remaining.indexOf("# Input Context");
  if (sysPromptIndex !== -1 && inputContextIndex !== -1) {
    result.systemPrompt = remaining.substring(sysPromptIndex + 15, inputContextIndex).trim();
    result.userPromptTemplate = remaining.substring(inputContextIndex + 15).trim();
  } else if (sysPromptIndex !== -1) {
    result.systemPrompt = remaining.substring(sysPromptIndex + 15).trim();
  } else {
    result.userPromptTemplate = remaining.trim();
  }
  return result;
}
function fillTemplate(template, variables) {
  let filled = template;
  for (const [key, value] of Object.entries(variables)) {
    const placeholder = new RegExp(`{{\\s*${key}\\s*}}`, "g");
    filled = filled.replace(placeholder, value);
  }
  return filled;
}
var DEFAULT_INGEST_SKILL = `---
name: Ingest
description: \u63D0\u53D6\u526A\u85CF\u6E90\u6587\u4EF6\uFF0C\u878D\u5408\u5408\u5E76\u81F3\u5DF2\u6709\u77E5\u8BC6\u5E93\u4E2D\u3002
version: 1.0.0
---

# System Prompt
\u4F60\u662F\u4E00\u540D\u4E25\u8C28\u7684\u4E2A\u4EBA\u77E5\u8BC6\u5E93\u6574\u7406\u4E13\u5BB6\u3002\u4F60\u7684\u4EFB\u52A1\u662F\u9605\u8BFB\u7ED9\u5B9A\u7684\u526A\u85CF\u6587\u7AE0\u5185\u5BB9\uFF0C\u63D0\u53D6\u51FA\u5173\u952E\u7684\u5B9E\u4F53\u3001\u6982\u5FF5\u3001\u7ED3\u8BBA\uFF0C\u5E76\u5C06\u5B83\u4EEC\u6709\u6761\u7406\u5730\u5408\u5E76\u5230\u5DF2\u6709\u7684 Wiki \u77E5\u8BC6\u5E93\u76EE\u5F55\u4E2D\u3002

\u8BF7\u4E25\u683C\u9075\u5B88\u4EE5\u4E0B SOP \u89C4\u8303\uFF1A
1. **\u5408\u5E76\u4F18\u5148**\uFF1A\u9996\u5148\u68C0\u67E5\u201C\u5DF2\u6709\u77E5\u8BC6\u76EE\u5F55\u5217\u8868\u201D\uFF0C\u5224\u65AD\u662F\u5426\u6709\u9AD8\u5EA6\u76F8\u5173\u7684\u8BDD\u9898/\u5B9E\u4F53\u9875\u9762\u3002\u5982\u679C\u6709\uFF0C\u4F60\u5E94\u8BE5\u751F\u6210\u5BF9\u5176\u8FDB\u884C\u7684\u4FEE\u6539\u65B9\u6848\uFF1B\u5982\u679C\u5B8C\u5168\u6CA1\u6709\uFF0C\u624D\u5EFA\u8BAE\u521B\u5EFA\u65B0\u9875\u9762\u3002
2. **\u751F\u6210\u53CC\u94FE**\uFF1A\u65B0\u751F\u6210\u6216\u66F4\u65B0\u7684\u6587\u7AE0\u5185\u5BB9\u4E2D\uFF0C\u6D89\u53CA\u5176\u4ED6\u77E5\u8BC6\u5E93\u5DF2\u6709\u7684\u5B9E\u4F53\u6216\u6982\u5FF5\u65F6\uFF0C\u5FC5\u987B\u4F7F\u7528 Obsidian \u53CC\u94FE\u683C\u5F0F\uFF08\u5982 [[Entity_Name]]\uFF09\u3002
3. **\u5143\u6570\u636E**\uFF1A\u5FC5\u987B\u63D0\u4F9B\u7B80\u660E\u627C\u8981\u7684\u4E00\u53E5\u8BDD Summary \u63CF\u8FF0\u8BE5\u5B9E\u4F53\u6216\u6982\u5FF5\u3002
4. **\u6807\u8BB0\u77DB\u76FE**\uFF1A\u5982\u679C\u65B0\u526A\u85CF\u7684\u4FE1\u606F\u4E0E\u5DF2\u6709\u77E5\u8BC6\u5E93\u9875\u9762\u91CC\u7684\u5185\u5BB9\u5B58\u5728\u77DB\u76FE\uFF0C\u5FC5\u987B\u5728\u8F93\u51FA\u4E2D\u663E\u5F0F\u6807\u8BB0\u51FA\u6765\uFF0C\u5E76\u5728\u51B2\u7A81\u9875\u9762\u4E0A\u65B9\u52A0\u4E0A\u8B66\u544A\u3002

# Input Context
## \u5DF2\u6709\u77E5\u8BC6\u76EE\u5F55\u5217\u8868
{{index_content}}

## \u5F85\u5BFC\u5165\u526A\u85CF\u5185\u5BB9
{{clipping_content}}

# Output Format
\u8BF7\u52A1\u5FC5\u8FD4\u56DE\u4EE5\u4E0B JSON \u683C\u5F0F\u6570\u636E\uFF0C\u4E0D\u8981\u5305\u542B\u4EFB\u4F55\u989D\u5916\u7684 markdown \u6807\u8BB0\uFF08\u5982 \`\`\`json \u7B49\u5305\u88F9\uFF09\uFF1A
{
  "operations": [
    {
      "action": "create", // "modify" \u6216\u8005\u662F "create"
      "path": "wiki/Entity_Karpathy.md",
      "title": "Andrej Karpathy",
      "content": "# Andrej Karpathy\\n...\u8FD9\u91CC\u662F\u66F4\u65B0\u540E\u7684\u5B8C\u6574 Markdown \u5185\u5BB9..."
    }
  ],
  "index_updates": [
    {
      "path": "wiki/Entity_Karpathy.md",
      "summary": "\u66F4\u65B0\u540E\u7684\u4E00\u53E5\u8BDD\u603B\u7ED3\u63CF\u8FF0..."
    }
  ],
  "contradictions": [
    {
      "page": "wiki/LLM_Wiki.md",
      "reason": "\u65B0\u6587\u7AE0\u6307\u51FA\u5185\u5BB9\u4E0E\u4E4B\u524D\u9875\u9762\u4E2D\u8BB0\u5F55\u7684\u51B2\u7A81\u3002"
    }
  ]
}
`;
var DEFAULT_QUERY_SKILL = `---
name: Query
description: \u5BF9\u8BDD\u5F15\u64CE\uFF0C\u4ECE\u7D22\u5F15\u5217\u8868\u4E2D\u5B9A\u4F4D\u5E76\u95EE\u7B54\u3002
version: 1.0.0
---

# System Prompt
\u4F60\u662F\u4E00\u4E2A\u667A\u80FD Wiki \u95EE\u7B54\u52A9\u7406\u3002\u4F60\u7684\u4EFB\u52A1\u662F\u6839\u636E\u7528\u6237\u63D0\u4F9B\u7684\u76F8\u5173 Wiki \u9875\u9762\u5185\u5BB9\uFF0C\u56DE\u7B54\u7528\u6237\u7684\u95EE\u9898\u3002
\u4F60\u5FC5\u987B\u786E\u4FDD\uFF1A
1. **\u53EA\u57FA\u4E8E\u7ED9\u5B9A\u7684\u9875\u9762\u5185\u5BB9\u56DE\u7B54**\uFF0C\u5982\u679C\u5185\u5BB9\u4E2D\u4E0D\u5305\u542B\u7B54\u6848\uFF0C\u8BF7\u76F4\u63A5\u8BF4\u201C\u77E5\u8BC6\u5E93\u4E2D\u6682\u65E0\u76F8\u5173\u8BB0\u5F55\uFF0C\u5EFA\u8BAE\u5BFC\u5165\u65B0\u526A\u85CF\u201D\u3002
2. **\u6807\u660E\u51FA\u5904**\uFF1A\u5728\u56DE\u7B54\u7684\u5173\u952E\u53E5\u672B\u5C3E\uFF0C\u4F7F\u7528\u7C7B\u4F3C [[Page_Name#Section]] \u7684\u65B9\u5F0F\u6807\u6CE8\u5F15\u7528\u7684\u77E5\u8BC6\u5E93\u9875\u9762\u3002
3. **\u4FDD\u6301 Obsidian \u683C\u5F0F**\uFF1A\u56DE\u7B54\u76F4\u63A5\u4F7F\u7528 Markdown \u683C\u5F0F\uFF0C\u4FDD\u7559\u6BB5\u843D\u6392\u7248\u3002

# Input Context
## \u7528\u6237\u63D0\u95EE
{{user_question}}

## \u76F8\u5173 Wiki \u9875\u9762\u5185\u5BB9
{{page_contents}}

# Output Format
\u8BF7\u76F4\u63A5\u8F93\u51FA Markdown \u683C\u5F0F\u7684\u56DE\u7B54\u6B63\u6587\uFF0C\u5728\u53E5\u672B\u6DFB\u52A0\u76F8\u5E94\u7684 [[\u53CC\u94FE\u5F15\u7528]]\u3002
`;
var DEFAULT_SAVEPAGE_SKILL = `---
name: SavePage
description: \u5C06\u5BF9\u8BDD\u95EE\u7B54\u5185\u5BB9\u53BB\u8BDD\u8BED\u5316\uFF0C\u63D0\u70BC\u4E3A\u6807\u51C6\u7684 Wiki \u9875\u9762\u3002
version: 1.0.0
---

# System Prompt
\u4F60\u662F\u4E00\u540D Wiki \u9875\u9762\u7CBE\u70BC\u4E13\u5BB6\u3002\u4F60\u7684\u4EFB\u52A1\u662F\u8BFB\u53D6\u7528\u6237\u7684\u63D0\u95EE\u4E0E\u5BF9\u5E94\u7684\u52A9\u624B\u56DE\u7B54\uFF0C\u5C06\u5176\u8F6C\u5316\u4E3A\u4E00\u7BC7\u683C\u5F0F\u89C4\u8303\u3001\u5BA2\u89C2\u9648\u8FF0\u3001\u7ED3\u6784\u6E05\u6670\u7684 Wiki \u77E5\u8BC6\u5E93 Markdown \u9875\u9762\u3002

\u8BF7\u9075\u5B88\u4EE5\u4E0B\u8F6C\u6362\u89C4\u5219\uFF1A
1. **\u53BB\u8BDD\u8BED\u5316**\uFF1A\u79FB\u9664\u6240\u6709\u8BF8\u5982\u201C\u597D\u7684\uFF0C\u4E3A\u60A8\u89E3\u7B54\u5982\u4E0B\uFF1A\u201D\u3001\u201C\u5F53\u7136\u53EF\u4EE5\uFF0C\u5BF9\u6BD4\u53D1\u73B0...\u201D\u7B49\u804A\u5929\u53E3\u543B\u6216\u5BD2\u6684\u8BED\u3002
2. **\u89C4\u8303\u547D\u540D\u4E0E\u5927\u7EB2**\uFF1A\u4E3B\u6807\u9898\u4F7F\u7528 # \u7B49\u7EA7\uFF0C\u5185\u90E8\u4F7F\u7528 ## \u548C ### \u8FDB\u884C\u8BED\u4E49\u5212\u5206\u3002
3. **\u4FDD\u7559\u5E76\u4FEE\u6B63\u53CC\u94FE**\uFF1A\u4FDD\u7559\u539F\u56DE\u7B54\u4E2D\u7684 [[\u53CC\u94FE\u5F15\u7528]]\uFF0C\u5E76\u57FA\u4E8E\u4F60\u7684\u5168\u5C40\u77E5\u8BC6\u5BF9\u94FE\u63A5\u540D\u79F0\u8FDB\u884C\u6807\u51C6\u5316\u3002
4. **\u751F\u6210\u6458\u8981\u4E0E\u522B\u540D**\uFF1A\u751F\u6210\u9002\u5408 Obsidian Frontmatter \u683C\u5F0F\u7684 aliases\uFF08\u522B\u540D\u5217\u8868\uFF09\u548C\u4E00\u53E5\u8BDD summary\u3002

# Input Context
## \u7528\u6237\u63D0\u95EE
{{user_question}}

## \u539F\u59CB\u56DE\u7B54\u5185\u5BB9
{{assistant_answer}}

# Output Format
\u8BF7\u4E25\u683C\u8FD4\u56DE\u4EE5\u4E0B JSON \u683C\u5F0F\u6570\u636E\uFF0C\u4E0D\u8981\u5305\u542B\u4EFB\u4F55\u989D\u5916\u7684 Markdown \u5305\u88F9\uFF1A
{
  "title": "PageTitle", // \u63A8\u8350\u7684\u6587\u4EF6\u6807\u9898\u540D
  "frontmatter": {
    "aliases": ["\u522B\u540D"],
    "summary": "\u4E00\u53E5\u8BDD\u6458\u8981"
  },
  "content": "# \u6807\u9898\\n...\u6B63\u6587\u5185\u5BB9..."
}
`;
var DEFAULT_LINT_SKILL = `---
name: Lint
description: \u77E5\u8BC6\u5065\u5EB7\u5EA6\u4F53\u68C0\uFF0C\u5BFB\u627E\u51B2\u7A81\u3001\u9648\u65E7\u4FE1\u606F\u548C\u5B64\u7ACB\u8282\u70B9\u3002
version: 1.0.0
---

# System Prompt
\u4F60\u662F\u4E00\u540D\u77E5\u8BC6\u5E93\u5BA1\u8BA1\u5458\u3002\u4F60\u7684\u4EFB\u52A1\u662F\u5BF9\u6BD4\u8F93\u5165\u7684 Wiki \u9875\u9762\u7FA4\u7EC4\uFF0C\u627E\u51FA\u4EE5\u4E0B\u51E0\u7C7B\u5065\u5EB7\u95EE\u9898\uFF1A
1. **\u4FE1\u606F\u77DB\u76FE (Contradiction)**\uFF1A\u4E0D\u540C\u7684\u9875\u9762\u5BF9\u540C\u4E00\u4E2A\u4E8B\u5B9E\u3001\u6570\u636E\u6709\u4E0D\u540C\u7684\u63CF\u8FF0\uFF08\u4F8B\u5982\uFF0C\u4E00\u4E2A\u5199\u6307\u6807\u4E3A22\uFF0C\u53E6\u4E00\u4E2A\u5199\u4E3A23\uFF09\u3002
2. **\u5B64\u7ACB\u8282\u70B9 (Orphan)**\uFF1A\u8BE5\u9875\u9762\u6CA1\u6709\u4EFB\u4F55\u5165\u7AD9\uFF08Inbound\uFF09\u53CC\u94FE\u5F15\u7528\uFF0C\u5BB9\u6613\u5728\u65E5\u5E38\u6D4F\u89C8\u4E2D\u8FF7\u5931\u3002
3. **\u9648\u65E7\u6216\u7A7A\u767D\u9875\u9762 (Stale)**\uFF1A\u5185\u5BB9\u8FC7\u4E8E\u7A7A\u6D1E\u6216\u88AB\u6807\u8BB0\u4E3A\u9700\u8981\u8865\u5145\u7684\u7A7A\u767D\u9875\u9762\u3002

# Input Context
## \u5F85\u4F53\u68C0 Wiki \u9875\u9762\u96C6
{{group_pages}}

# Output Format
\u8BF7\u4E25\u683C\u8FD4\u56DE\u4EE5\u4E0B JSON \u683C\u5F0F\u6570\u636E\uFF0C\u4E0D\u8981\u5305\u542B\u4EFB\u4F55\u989D\u5916\u7684\u5305\u88F9\u6216\u8BF4\u660E\uFF1A
{
  "contradictions": [
    {
      "files": ["wiki/PageA.md", "wiki/PageB.md"],
      "description": "\u77DB\u76FE\u63CF\u8FF0"
    }
  ],
  "orphans": [
    "wiki/PageC.md"
  ],
  "suggestions": [
    "\u5EFA\u8BAE\u5728 wiki/PageD.md \u4E2D\u6DFB\u52A0\u5BF9 wiki/PageC.md \u7684\u5F15\u7528\u3002"
  ]
}
`;

// src/chat_view.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_CHAT = "genwiki-chat-view";
var GenWikiChatView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "GenWiki \u667A\u80FD\u95EE\u7B54";
  }
  getIcon() {
    return "cpu";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("genwiki-chat-view");
    const headerRow = container.createDiv({ cls: "genwiki-header-row" });
    headerRow.createEl("h3", { text: "\u{1F4AC} GenWiki \u667A\u80FD\u95EE\u7B54" });
    const startIngestBtn = headerRow.createEl("button", {
      cls: "genwiki-top-ingest-btn mod-cta",
      text: "\u{1F4E5} \u5F00\u59CB\u5904\u7406\u526A\u85CF"
    });
    startIngestBtn.addEventListener("click", () => {
      void (async () => {
        startIngestBtn.disabled = true;
        startIngestBtn.setText("\u6B63\u5728\u6574\u7406\u4E2D...");
        new import_obsidian2.Notice("\u6B63\u5728\u5F00\u59CB\u626B\u63CF\u5E76\u6574\u7406\u526A\u85CF\u8D44\u6599...");
        try {
          await this.plugin.runIngest();
          new import_obsidian2.Notice("\u{1F389} \u526A\u85CF\u6574\u7406\u5B8C\u6210\uFF01");
        } catch (e) {
          new import_obsidian2.Notice(`Ingest \u5931\u8D25: ${e.message}`);
          console.error(e);
        } finally {
          startIngestBtn.disabled = false;
          startIngestBtn.setText("\u{1F4E5} \u5F00\u59CB\u5904\u7406\u526A\u85CF");
        }
      })();
    });
    this.historyContainer = container.createDiv({ cls: "genwiki-chat-history" });
    this.historyContainer.addEventListener("click", (e) => {
      const target = e.target;
      if (target && target.tagName === "A" && target.hasClass("internal-link")) {
        e.preventDefault();
        const href = target.getAttribute("href");
        if (href) {
          void this.plugin.app.workspace.openLinkText(href, "", true);
        }
      }
    });
    this.appendMessage("assistant", "\u4F60\u597D\uFF01\u6211\u662F\u4F60\u7684 GenWiki \u52A9\u624B\u3002\u6211\u53EF\u4EE5\u57FA\u4E8E\u4F60\u5F53\u524D Wiki \u77E5\u8BC6\u5E93\u5185\u7684\u6982\u5FF5\u548C\u5B9E\u4F53\u56DE\u7B54\u4F60\u7684\u95EE\u9898\u3002\u95EE\u7B54\u4EA7\u751F\u7684\u6D1E\u5BDF\u652F\u6301\u4E00\u952E\u4FDD\u5B58\u4E3A\u6B63\u5F0F\u77E5\u8BC6\u6587\u4EF6\u3002");
    const inputContainer = container.createDiv({ cls: "genwiki-chat-input-container" });
    this.inputArea = inputContainer.createEl("textarea", {
      cls: "genwiki-chat-input",
      placeholder: "\u5411 Wiki \u63D0\u95EE..."
    });
    this.sendButton = inputContainer.createEl("button", { text: "\u53D1\u9001" });
    this.sendButton.addEventListener("click", () => {
      void this.handleSend();
    });
    this.inputArea.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        void this.handleSend();
      }
    });
  }
  async onClose() {
  }
  appendMessage(sender, text) {
    const msgDiv = this.historyContainer.createDiv({
      cls: `genwiki-chat-message genwiki-chat-message-${sender}`
    });
    msgDiv.setText(text);
    this.historyContainer.scrollTop = this.historyContainer.scrollHeight;
    return msgDiv;
  }
  async handleSend() {
    const query = this.inputArea.value.trim();
    if (!query)
      return;
    this.appendMessage("user", query);
    this.inputArea.value = "";
    const assistantMsgDiv = this.appendMessage("assistant", "\u6B63\u5728\u601D\u8003\u68C0\u7D22\u4E2D...");
    this.sendButton.disabled = true;
    this.inputArea.disabled = true;
    try {
      const answer = await this.plugin.executeQuery(query);
      assistantMsgDiv.empty();
      const renderDiv = assistantMsgDiv.createDiv();
      await import_obsidian2.MarkdownRenderer.render(this.app, answer, renderDiv, "", this);
      const actionsDiv = assistantMsgDiv.createDiv({ cls: "genwiki-msg-actions" });
      const copyBtn = actionsDiv.createEl("button", {
        cls: "genwiki-copy-btn",
        text: "\u{1F4CB} \u590D\u5236"
      });
      copyBtn.addEventListener("click", () => {
        navigator.clipboard.writeText(answer);
        new import_obsidian2.Notice("\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F\uFF01");
      });
      const isNoRecord = answer.includes("\u6682\u65E0\u76F8\u5173\u8BB0\u5F55") || answer.includes("\u6682\u65E0\u76F8\u5173") || answer.includes("\u6682\u65E0\u76F8\u5173Wiki");
      if (!isNoRecord) {
        const saveBtn = actionsDiv.createEl("button", {
          cls: "genwiki-save-btn mod-cta",
          text: "\u{1F4BE} \u4FDD\u5B58\u4E3A Wiki \u9875\u9762"
        });
        saveBtn.addEventListener("click", () => {
          void (async () => {
            saveBtn.disabled = true;
            saveBtn.setText("\u6B63\u5728\u63D0\u70BC\u5F52\u7EB3...");
            try {
              await this.saveResponseToWiki(query, answer);
              saveBtn.setText("\u2705 \u5DF2\u6210\u529F\u4FDD\u5B58");
            } catch (err) {
              new import_obsidian2.Notice(`\u4FDD\u5B58\u5931\u8D25: ${err.message}`);
              saveBtn.disabled = false;
              saveBtn.setText("\u{1F4BE} \u4FDD\u5B58\u4E3A Wiki \u9875\u9762");
            }
          })();
        });
      }
    } catch (err) {
      assistantMsgDiv.setText(`\u9519\u8BEF: ${err.message}`);
      console.error(err);
    } finally {
      this.sendButton.disabled = false;
      this.inputArea.disabled = false;
      this.historyContainer.scrollTop = this.historyContainer.scrollHeight;
    }
  }
  // P2: Save to Wiki orchestration
  async saveResponseToWiki(question, answer) {
    const skillFile = this.plugin.app.vault.getAbstractFileByPath((0, import_obsidian2.normalizePath)(`${this.plugin.settings.wikiDir}/_skills/SavePage.md`));
    if (!(skillFile instanceof import_obsidian2.TFile)) {
      throw new Error("SavePage skill template missing.");
    }
    const skillRaw = await this.plugin.app.vault.read(skillFile);
    const skill = parseSkillMarkdown(skillRaw);
    const userPrompt = fillTemplate(skill.userPromptTemplate, {
      user_question: question,
      assistant_answer: answer
    });
    new import_obsidian2.Notice("\u6B63\u5728\u8FDB\u884C\u683C\u5F0F\u6574\u7406\u4E0E\u53BB\u8BDD\u8BED\u5316...");
    const response = await this.plugin.llmClient.complete(userPrompt, skill.systemPrompt);
    const cleanResponse = LLMClient.cleanJsonString(response);
    const parsed = (() => {
      try {
        return JSON.parse(cleanResponse);
      } catch (e) {
        console.error("Failed to parse SavePage response JSON", cleanResponse, e);
        throw new Error("\u6A21\u578B\u751F\u6210\u7684 JSON \u683C\u5F0F\u4E0D\u89C4\u8303\uFF0C\u8BF7\u91CD\u65B0\u5C1D\u8BD5\u3002");
      }
    })();
    if (typeof parsed !== "object" || parsed === null) {
      throw new Error("\u6A21\u578B\u751F\u6210\u7684 JSON \u4E0D\u662F\u5BF9\u8C61\u7C7B\u578B\uFF0C\u65E0\u6CD5\u4FDD\u5B58\u3002");
    }
    const result = parsed;
    const title = typeof result.title === "string" ? result.title : void 0;
    const content = typeof result.content === "string" ? result.content : void 0;
    const frontmatter = typeof result.frontmatter === "object" && result.frontmatter !== null ? result.frontmatter : void 0;
    if (!title || !content) {
      throw new Error("\u4FDD\u5B58\u7684\u6570\u636E\u4E2D\u7F3A\u5C11\u5FC5\u8981\u7684\u6587\u4EF6\u6807\u9898(title)\u6216\u5185\u5BB9(content)\u3002");
    }
    const fileName = title.replace(/[\\/:*?"<>|]/g, "_");
    const destPath = (0, import_obsidian2.normalizePath)(`${this.plugin.settings.wikiDir}/${fileName}.md`);
    const fileExists = this.plugin.app.vault.getAbstractFileByPath(destPath);
    if (fileExists) {
      throw new Error(`\u6587\u4EF6 ${destPath} \u5DF2\u5B58\u5728\uFF0C\u65E0\u6CD5\u8986\u76D6\u3002\u8BF7\u5728\u4FA7\u8FB9\u680F\u624B\u52A8\u6539\u540D\u91CD\u8BD5\u3002`);
    }
    const fm = frontmatter || {};
    const aliasesRaw = fm["aliases"];
    const aliasesArr = Array.isArray(aliasesRaw) ? aliasesRaw.map((a) => String(a)) : [];
    const aliasesStr = aliasesArr.length > 0 ? JSON.stringify(aliasesArr) : "[]";
    const summaryStr = typeof fm["summary"] === "string" ? fm["summary"] : "";
    const fullContent = `---
	aliases: ${aliasesStr}
	summary: "${summaryStr.replace(/"/g, '\\"')}"
	last_updated: ${(/* @__PURE__ */ new Date()).toISOString()}
	status: active
	---

	${content}`;
    await this.plugin.app.vault.create(destPath, fullContent);
    const db = await this.plugin.loadDatabase();
    const fileHash = await this.plugin.calculateHash(fullContent);
    const linksTo = this.plugin.extractLinks(fullContent);
    db.wiki_pages[destPath] = {
      path: destPath,
      title,
      aliases: aliasesArr || [],
      type: "general",
      summary: summaryStr,
      status: "active",
      last_updated: (/* @__PURE__ */ new Date()).toISOString(),
      sha256: fileHash,
      links_to: linksTo,
      links_from: [],
      claims: [
        {
          clipping_path: "ChatInteraction",
          line_range: "all",
          paragraph_summary: summaryStr
        }
      ],
      audit: {
        created_at: (/* @__PURE__ */ new Date()).toISOString(),
        last_compiled_cost_usd: 0.01,
        history: [
          {
            timestamp: (/* @__PURE__ */ new Date()).toISOString(),
            action: "create",
            trigger: "chat_save",
            source: "ChatInteraction"
          }
        ]
      }
    };
    for (const outgoing of linksTo) {
      const targetPage = db.wiki_pages[outgoing];
      if (targetPage && !targetPage.links_from.includes(destPath)) {
        targetPage.links_from.push(destPath);
      }
    }
    await this.plugin.saveDatabase(db);
    await this.plugin.rebuildIndexMd(db);
    await this.plugin.logAction("chat_save", title);
    new import_obsidian2.Notice(`\u{1F389} \u77E5\u8BC6\u70B9 [[${title}]] \u5DF2\u6210\u529F\u5F55\u5165 Wiki\uFF01`);
    const newFile = this.plugin.app.vault.getAbstractFileByPath(destPath);
    if (newFile instanceof import_obsidian2.TFile) {
      const leaf = this.plugin.app.workspace.getLeaf(false);
      if (leaf)
        await leaf.openFile(newFile);
    }
  }
};

// src/main.ts
var GenWikiPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.llmClient = new LLMClient(this.settings);
    this.registerView(
      VIEW_TYPE_CHAT,
      (leaf) => new GenWikiChatView(leaf, this)
    );
    await this.initFolders();
    await this.initDefaultTemplates();
    this.addSettingTab(new GenWikiSettingTab(this.app, this));
    this.addRibbonIcon("cpu", "GenWiki: Open Chat Panel", () => {
      this.activateView();
    });
    this.addCommand({
      id: "ingest-clippings",
      name: "Ingest Clippings (\u589E\u91CF\u5BFC\u5165\u526A\u85CF)",
      callback: async () => {
        new import_obsidian3.Notice("\u5F00\u59CB\u6574\u7406\u526A\u85CF\u8D44\u6599...");
        try {
          await this.runIngest();
        } catch (e) {
          new import_obsidian3.Notice(`Ingest \u5931\u8D25: ${e.message}`);
          console.error(e);
        }
      }
    });
    this.addCommand({
      id: "query-wiki",
      name: "Query Wiki (\u667A\u80FD\u77E5\u8BC6\u68C0\u7D22\u4E0E\u5BF9\u8BDD)",
      callback: () => {
        new QueryModal(this.app, this).open();
      }
    });
    this.addCommand({
      id: "lint-wiki",
      name: "Lint Wiki (\u5065\u5EB7\u5EA6\u4F53\u68C0)",
      callback: async () => {
        new import_obsidian3.Notice("\u6B63\u5728\u5F00\u59CB\u77E5\u8BC6\u5E93\u5065\u5EB7\u5BA1\u8BA1...");
        try {
          await this.runLint();
        } catch (e) {
          new import_obsidian3.Notice(`Lint \u5931\u8D25: ${e.message}`);
          console.error(e);
        }
      }
    });
    this.addCommand({
      id: "open-chat-view",
      name: "Open Chat Panel (\u6253\u5F00\u667A\u80FD\u95EE\u7B54\u4FA7\u8FB9\u680F)",
      callback: () => this.activateView()
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.llmClient = new LLMClient(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CHAT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  // Helper to calculate SHA256 in a pure client environment
  async calculateHash(text) {
    const msgBuffer = new TextEncoder().encode(text);
    const hashBuffer = await crypto.subtle.digest("SHA-256", msgBuffer);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map((b) => b.toString(16).padStart(2, "0")).join("");
  }
  async initFolders() {
    const folders = [
      this.settings.clippingsDir,
      `${this.settings.clippingsDir}/Archived`,
      this.settings.wikiDir,
      `${this.settings.wikiDir}/_skills`,
      `${this.settings.wikiDir}/_agents`,
      `${this.settings.wikiDir}/_database`
    ];
    for (const folder of folders) {
      const normalized = (0, import_obsidian3.normalizePath)(folder);
      const exists = this.app.vault.getAbstractFileByPath(normalized);
      if (!exists) {
        await this.app.vault.createFolder(normalized);
      }
    }
  }
  async initDefaultTemplates() {
    const templates = [
      { path: `${this.settings.wikiDir}/_skills/Ingest.md`, content: DEFAULT_INGEST_SKILL },
      { path: `${this.settings.wikiDir}/_skills/Query.md`, content: DEFAULT_QUERY_SKILL },
      { path: `${this.settings.wikiDir}/_skills/SavePage.md`, content: DEFAULT_SAVEPAGE_SKILL },
      { path: `${this.settings.wikiDir}/_skills/Lint.md`, content: DEFAULT_LINT_SKILL }
    ];
    for (const t of templates) {
      const normalized = (0, import_obsidian3.normalizePath)(t.path);
      const file2 = this.app.vault.getAbstractFileByPath(normalized);
      if (!file2) {
        await this.app.vault.create(normalized, t.content);
      }
    }
    const claudePath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_agents/CLAUDE.md`);
    const file = this.app.vault.getAbstractFileByPath(claudePath);
    if (!file) {
      await this.app.vault.create(claudePath, `# CLAUDE.md

\u672C\u534F\u8BAE\u7EA6\u675F GenWiki \u5904\u7406\u77E5\u8BC6\u7684\u89C4\u8303\u3002`);
    }
    const indexPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/index.md`);
    if (!this.app.vault.getAbstractFileByPath(indexPath)) {
      await this.app.vault.create(indexPath, `# Knowledge Index

\u672C\u6587\u4EF6\u662F\u81EA\u52A8\u751F\u6210\u7684\u7D22\u5F15\u3002`);
    }
    const logPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/log.md`);
    if (!this.app.vault.getAbstractFileByPath(logPath)) {
      await this.app.vault.create(logPath, `# Action Audit Logs

\u8BB0\u5F55\u6BCF\u6B21\u77E5\u8BC6\u6574\u7406\u548C\u67E5\u8BE2\u3002`);
    }
  }
  async loadDatabase() {
    const dbPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_database/index.json`);
    const file = this.app.vault.getAbstractFileByPath(dbPath);
    if (file instanceof import_obsidian3.TFile) {
      const text = await this.app.vault.read(file);
      try {
        const parsed = JSON.parse(text);
        if (typeof parsed === "object" && parsed !== null && "wiki_pages" in parsed) {
          return parsed;
        }
        console.error("Database file has unexpected shape, resetting");
      } catch (e) {
        console.error("Failed to parse database file, resetting", e);
      }
    }
    return {
      version: "1.0.0",
      last_indexed: (/* @__PURE__ */ new Date()).toISOString(),
      clippings: {},
      wiki_pages: {}
    };
  }
  async saveDatabase(db) {
    const dbPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_database/index.json`);
    const file = this.app.vault.getAbstractFileByPath(dbPath);
    const content = JSON.stringify(db, null, 2);
    if (file instanceof import_obsidian3.TFile) {
      await this.app.vault.modify(file, content);
    } else {
      await this.app.vault.create(dbPath, content);
    }
  }
  async logAction(action, title) {
    const logPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/log.md`);
    const file = this.app.vault.getAbstractFileByPath(logPath);
    if (file instanceof import_obsidian3.TFile) {
      const dateStr = (/* @__PURE__ */ new Date()).toISOString().substring(0, 10);
      const entry = `
## [${dateStr}] ${action} | ${title}
`;
      await this.app.vault.append(file, entry);
    }
  }
  // Extract outgoing double links from text
  extractLinks(text) {
    const links = [];
    const regex = /\[\[(.*?)\]\]/g;
    let match;
    while ((match = regex.exec(text)) !== null) {
      let link = match[1];
      if (link.includes("|")) {
        link = link.split("|")[0];
      }
      if (link.includes("#")) {
        link = link.split("#")[0];
      }
      const normalizedLink = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/${link.trim()}.md`);
      if (!links.includes(normalizedLink)) {
        links.push(normalizedLink);
      }
    }
    return links;
  }
  // Regenerate the main index.md file based on database contents
  async rebuildIndexMd(db) {
    const indexPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/index.md`);
    const file = this.app.vault.getAbstractFileByPath(indexPath);
    if (!(file instanceof import_obsidian3.TFile))
      return;
    let content = `# Knowledge Index

\u6B64\u9875\u9762\u7531 GenWiki \u81EA\u52A8\u66F4\u65B0\uFF0C\u5C55\u793A\u5168\u90E8\u5F52\u6863\u77E5\u8BC6\u70B9\u7684\u7D22\u5F15\u56FE\u8C31\u3002

## \u6982\u5FF5 (Concepts)
`;
    const concepts = Object.values(db.wiki_pages).filter((p) => p.type === "concept" && p.status !== "archived");
    const entities = Object.values(db.wiki_pages).filter((p) => p.type === "entity" && p.status !== "archived");
    const generals = Object.values(db.wiki_pages).filter((p) => p.type === "general" && p.status !== "archived");
    for (const p of concepts) {
      content += `* [[${p.title}]] - *${p.summary}*
`;
    }
    content += `
## \u5B9E\u4F53 (Entities)
`;
    for (const p of entities) {
      content += `* [[${p.title}]] - *${p.summary}*
`;
    }
    content += `
## \u5176\u4ED6\u9875\u9762 (General Pages)
`;
    for (const p of generals) {
      content += `* [[${p.title}]] - *${p.summary}*
`;
    }
    await this.app.vault.modify(file, content);
  }
  // P1: Ingest Process
  async runIngest() {
    const clippingsFolder = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(this.settings.clippingsDir));
    if (!(clippingsFolder instanceof import_obsidian3.TFolder)) {
      throw new Error(`Clippings directory ${this.settings.clippingsDir} does not exist.`);
    }
    const db = await this.loadDatabase();
    const files = clippingsFolder.children;
    const mdFiles = files.filter((f) => f instanceof import_obsidian3.TFile && f.extension === "md");
    let processedAny = false;
    for (const mdFile of mdFiles) {
      const relativePath = mdFile.path;
      if (relativePath.includes("/Archived/"))
        continue;
      const clippingMeta = db.clippings[relativePath];
      if (clippingMeta && clippingMeta.status === "processed")
        continue;
      const content = await this.app.vault.read(mdFile);
      const hash = await this.calculateHash(content);
      const indexFile = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/index.md`));
      const indexContent = indexFile instanceof import_obsidian3.TFile ? await this.app.vault.read(indexFile) : "";
      const skillFile = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_skills/Ingest.md`));
      if (!(skillFile instanceof import_obsidian3.TFile)) {
        throw new Error("Ingest skill template missing.");
      }
      const skillRaw = await this.app.vault.read(skillFile);
      const skill = parseSkillMarkdown(skillRaw);
      const userPrompt = fillTemplate(skill.userPromptTemplate, {
        index_content: indexContent,
        clipping_content: content
      });
      new import_obsidian3.Notice(`\u6B63\u5728\u901A\u8FC7 AI \u5206\u6790 ${mdFile.name}...`);
      const response = await this.llmClient.complete(userPrompt, skill.systemPrompt);
      const cleanResponse = LLMClient.cleanJsonString(response);
      let resultParsed;
      try {
        resultParsed = JSON.parse(cleanResponse);
      } catch (e) {
        console.error("Failed to parse LLM Response JSON", cleanResponse, e);
        new import_obsidian3.Notice(`\u6A21\u578B\u8FD4\u56DE\u7684 JSON \u683C\u5F0F\u4E0D\u89C4\u8303\uFF0C\u8BF7\u91CD\u8BD5\uFF01`);
        db.clippings[relativePath] = {
          path: relativePath,
          sha256: hash,
          ingest_date: (/* @__PURE__ */ new Date()).toISOString(),
          status: "failed",
          destinations: []
        };
        await this.saveDatabase(db);
        continue;
      }
      if (typeof resultParsed !== "object" || resultParsed === null) {
        new import_obsidian3.Notice(`\u6A21\u578B\u8FD4\u56DE\u7684 JSON \u683C\u5F0F\u4E0D\u89C4\u8303\uFF08\u975E\u5BF9\u8C61\uFF09\uFF0C\u8BF7\u91CD\u8BD5\uFF01`);
        db.clippings[relativePath] = {
          path: relativePath,
          sha256: hash,
          ingest_date: (/* @__PURE__ */ new Date()).toISOString(),
          status: "failed",
          destinations: []
        };
        await this.saveDatabase(db);
        continue;
      }
      const result = resultParsed;
      const destinations = [];
      const operations = Array.isArray(result.operations) ? result.operations : [];
      for (const opRaw of operations) {
        if (typeof opRaw !== "object" || opRaw === null)
          continue;
        const op = opRaw;
        const action = typeof op.action === "string" ? op.action : "unknown";
        const opPath = typeof op.path === "string" ? op.path : void 0;
        const opContent = typeof op.content === "string" ? op.content : void 0;
        const opTitle = typeof op.title === "string" ? op.title : void 0;
        if (!opPath)
          continue;
        const destPath = (0, import_obsidian3.normalizePath)(opPath);
        destinations.push(destPath);
        const opFile = this.app.vault.getAbstractFileByPath(destPath);
        if (action === "create" || !opFile) {
          const parts = destPath.split("/");
          if (parts.length > 1) {
            const parentDir = parts.slice(0, parts.length - 1).join("/");
            if (!this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(parentDir))) {
              await this.app.vault.createFolder((0, import_obsidian3.normalizePath)(parentDir));
            }
          }
          await this.app.vault.create(destPath, opContent || "");
        } else if (opFile instanceof import_obsidian3.TFile) {
          await this.app.vault.modify(opFile, opContent || "");
        }
        const fileContent = opContent || "";
        const fileHash = await this.calculateHash(fileContent);
        const linksTo = this.extractLinks(fileContent);
        const indexUpdates = Array.isArray(result.index_updates) ? result.index_updates : [];
        const idxUpdateRaw = indexUpdates.find((iu) => typeof iu === "object" && iu !== null && iu.path === opPath);
        const idxUpdate = typeof idxUpdateRaw === "object" && idxUpdateRaw !== null ? idxUpdateRaw : {};
        const existingPage = db.wiki_pages[destPath];
        const auditHistory = existingPage?.audit.history || [];
        auditHistory.push({
          timestamp: (/* @__PURE__ */ new Date()).toISOString(),
          action,
          trigger: "ingest",
          source: relativePath
        });
        const idxAliasesRaw = idxUpdate["aliases"];
        const idxAliases = Array.isArray(idxAliasesRaw) ? idxAliasesRaw.map((a) => String(a)) : existingPage?.aliases || [];
        const idxTypeRaw = typeof idxUpdate["type"] === "string" ? idxUpdate["type"] : existingPage?.type;
        const idxType = idxTypeRaw === "concept" || idxTypeRaw === "entity" || idxTypeRaw === "general" ? idxTypeRaw : "general";
        const idxSummary = typeof idxUpdate["summary"] === "string" ? idxUpdate["summary"] : existingPage?.summary || "\u81EA\u52A8\u751F\u6210\u7684\u4FE1\u606F\u6761\u76EE\u3002";
        db.wiki_pages[destPath] = {
          path: destPath,
          title: opTitle || (opFile instanceof import_obsidian3.TFile ? opFile.name.replace(".md", "") : "Untitled"),
          aliases: idxAliases,
          type: idxType,
          summary: idxSummary,
          status: "active",
          last_updated: (/* @__PURE__ */ new Date()).toISOString(),
          sha256: fileHash,
          links_to: linksTo,
          links_from: existingPage?.links_from || [],
          claims: [
            {
              clipping_path: relativePath,
              line_range: "all",
              paragraph_summary: idxSummary || "\u6E90\u81EA\u526A\u85CF\u7684\u603B\u7ED3"
            }
          ],
          audit: {
            created_at: existingPage?.audit.created_at || (/* @__PURE__ */ new Date()).toISOString(),
            last_compiled_cost_usd: 0.01,
            history: auditHistory
          }
        };
      }
      for (const pagePath of destinations) {
        const page = db.wiki_pages[pagePath];
        if (page) {
          for (const outgoing of page.links_to) {
            const targetPage = db.wiki_pages[outgoing];
            if (targetPage && !targetPage.links_from.includes(pagePath)) {
              targetPage.links_from.push(pagePath);
            }
          }
        }
      }
      db.clippings[relativePath] = {
        path: relativePath,
        sha256: hash,
        ingest_date: (/* @__PURE__ */ new Date()).toISOString(),
        status: "processed",
        destinations
      };
      await this.logAction("ingest", mdFile.name);
      const archivedPath = (0, import_obsidian3.normalizePath)(`${this.settings.clippingsDir}/Archived/${mdFile.name}`);
      await this.app.vault.rename(mdFile, archivedPath);
      processedAny = true;
    }
    if (processedAny) {
      await this.saveDatabase(db);
      await this.rebuildIndexMd(db);
      new import_obsidian3.Notice("\u{1F389} \u526A\u85CF\u6574\u7406\u5408\u5E76\u5B8C\u6210\uFF01\u7D22\u5F15\u5DF2\u5237\u65B0\u3002");
    } else {
      new import_obsidian3.Notice("\u6CA1\u6709\u627E\u5230\u672A\u5904\u7406\u7684\u526A\u85CF\u6587\u4EF6\uFF01");
    }
  }
  // P1: Query core execution
  async executeQuery(question) {
    const db = await this.loadDatabase();
    const querySkillFile = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_skills/Query.md`));
    if (!(querySkillFile instanceof import_obsidian3.TFile)) {
      throw new Error("Query skill template missing.");
    }
    const skillRaw = await this.app.vault.read(querySkillFile);
    const skill = parseSkillMarkdown(skillRaw);
    const keywords = question.toLowerCase().split(/\s+/);
    const matchingPages = [];
    for (const page of Object.values(db.wiki_pages)) {
      const matches = keywords.some(
        (kw) => page.title.toLowerCase().includes(kw) || page.summary.toLowerCase().includes(kw) || page.aliases.some((alias) => alias.toLowerCase().includes(kw))
      );
      if (matches) {
        matchingPages.push(page);
      }
    }
    const pagesToRead = matchingPages.length > 0 ? matchingPages.slice(0, 5) : Object.values(db.wiki_pages).slice(0, 5);
    let combinedContents = "";
    for (const p of pagesToRead) {
      const file = this.app.vault.getAbstractFileByPath(p.path);
      if (file instanceof import_obsidian3.TFile) {
        const content = await this.app.vault.read(file);
        combinedContents += `
=== FILE: ${p.path} ===
${content}
`;
      }
    }
    if (!combinedContents.trim()) {
      combinedContents = "\uFF08\u6682\u65E0\u76F8\u5173Wiki\u77E5\u8BC6\u5185\u5BB9\uFF0C\u8BF7\u5148Ingest\u5BFC\u5165\u526A\u85CF\uFF09";
    }
    const userPrompt = fillTemplate(skill.userPromptTemplate, {
      user_question: question,
      page_contents: combinedContents
    });
    const response = await this.llmClient.complete(userPrompt, skill.systemPrompt);
    await this.logAction("query", question);
    return response;
  }
  // P1: Lint Process
  async runLint() {
    const db = await this.loadDatabase();
    const activePages = Object.values(db.wiki_pages).filter((p) => p.status !== "archived");
    if (activePages.length === 0) {
      new import_obsidian3.Notice("Wiki\u4E2D\u6CA1\u6709\u4EFB\u4F55\u9875\u9762\uFF0C\u8BF7\u5148\u6267\u884C Ingest \u5BFC\u5165\uFF01");
      return;
    }
    const lintSkillFile = this.app.vault.getAbstractFileByPath((0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/_skills/Lint.md`));
    if (!(lintSkillFile instanceof import_obsidian3.TFile)) {
      throw new Error("Lint skill template missing.");
    }
    const skillRaw = await this.app.vault.read(lintSkillFile);
    const skill = parseSkillMarkdown(skillRaw);
    const batchSize = 5;
    const contradictions = [];
    const orphans = [];
    const suggestions = [];
    for (let i = 0; i < activePages.length; i += batchSize) {
      const batch = activePages.slice(i, i + batchSize);
      let groupPagesContent = "";
      for (const page of batch) {
        const file = this.app.vault.getAbstractFileByPath(page.path);
        if (file instanceof import_obsidian3.TFile) {
          const content = await this.app.vault.read(file);
          groupPagesContent += `
=== FILE: ${page.path} ===
${content}
`;
        }
      }
      const userPrompt = fillTemplate(skill.userPromptTemplate, {
        group_pages: groupPagesContent
      });
      new import_obsidian3.Notice(`\u6B63\u5728\u5BA1\u8BA1\u7B2C ${Math.floor(i / batchSize) + 1} \u7EC4\u77E5\u8BC6\u8282\u70B9...`);
      const response = await this.llmClient.complete(userPrompt, skill.systemPrompt);
      const cleanResponse = LLMClient.cleanJsonString(response);
      try {
        const parsed = JSON.parse(cleanResponse);
        if (typeof parsed === "object" && parsed !== null) {
          const resObj = parsed;
          if (Array.isArray(resObj.contradictions)) {
            const validContradictions = resObj.contradictions.filter((item) => typeof item === "object" && item !== null);
            contradictions.push(...validContradictions);
          }
          if (Array.isArray(resObj.orphans)) {
            const validOrphans = resObj.orphans.filter((item) => typeof item === "string").map(String);
            orphans.push(...validOrphans);
          }
          if (Array.isArray(resObj.suggestions)) {
            const validSuggestions = resObj.suggestions.filter((item) => typeof item === "string").map(String);
            suggestions.push(...validSuggestions);
          }
        }
      } catch (e) {
        console.error("Failed to parse Lint Response JSON", cleanResponse, e);
      }
    }
    const finalOrphans = orphans.filter((path) => {
      const page = db.wiki_pages[path];
      return !page || !Array.isArray(page.links_from) || page.links_from.length === 0;
    });
    const reportPath = (0, import_obsidian3.normalizePath)(`${this.settings.wikiDir}/Lint_Report.md`);
    let reportContent = `# GenWiki \u77E5\u8BC6\u5E93\u5065\u5EB7\u4F53\u68C0\u5BA1\u8BA1\u62A5\u544A

\u62A5\u544A\u751F\u6210\u65F6\u95F4: ${(/* @__PURE__ */ new Date()).toLocaleString()}

`;
    reportContent += `## 1. \u4FE1\u606F\u51B2\u7A81\u4E0E\u77DB\u76FE\u8B66\u544A (Contradictions)
`;
    if (contradictions.length > 0) {
      for (const cRaw of contradictions) {
        if (typeof cRaw !== "object" || cRaw === null)
          continue;
        const c = cRaw;
        const filesRaw = c["files"];
        const filesArr = Array.isArray(filesRaw) ? filesRaw.map((f) => String(f)) : [];
        const desc = typeof c["description"] === "string" ? c["description"] : "";
        reportContent += `* **\u6D89\u53CA\u6587\u4EF6**: ${filesArr.map((f) => `[[${f.replace(this.settings.wikiDir + "/", "").replace(".md", "")}]]`).join(", ")}
  * **\u77DB\u76FE\u63CF\u8FF0**: ${desc}
`;
      }
    } else {
      reportContent += `\u2705 \u672A\u68C0\u6D4B\u5230\u660E\u663E\u7684\u903B\u8F91\u51B2\u7A81\u6216\u6570\u636E\u77DB\u76FE\u3002
`;
    }
    reportContent += `
## 2. \u5B64\u7ACB\u8282\u70B9\u5217\u8868 (Orphan Pages)
`;
    if (finalOrphans.length > 0) {
      for (const path of finalOrphans) {
        const title = path.replace(this.settings.wikiDir + "/", "").replace(".md", "");
        reportContent += `* [[${title}]] - *\u65E0\u5176\u4ED6\u9875\u9762\u5F15\u7528*
`;
      }
    } else {
      reportContent += `\u2705 \u6240\u6709 Wiki \u9875\u9762\u5747\u6709\u5165\u7AD9\u94FE\u63A5\u5173\u8054\u3002
`;
    }
    reportContent += `
## 3. \u5173\u8054\u6784\u5EFA\u4E0E\u8865\u5168\u5EFA\u8BAE (Suggestions)
`;
    if (suggestions.length > 0) {
      for (const s of suggestions) {
        reportContent += `* ${s}
`;
      }
    } else {
      reportContent += `\u2705 \u76EE\u524D\u8FDE\u63A5\u56FE\u8C31\u5B8C\u6574\u6027\u826F\u597D\u3002
`;
    }
    const reportFile = this.app.vault.getAbstractFileByPath(reportPath);
    if (reportFile instanceof import_obsidian3.TFile) {
      await this.app.vault.modify(reportFile, reportContent);
    } else {
      await this.app.vault.create(reportPath, reportContent);
    }
    await this.logAction("lint", "Lint\u5065\u5EB7\u5BA1\u8BA1\u62A5\u544A");
    new import_obsidian3.Notice("\u{1F389} \u77E5\u8BC6\u5065\u5EB7\u4F53\u68C0\u5B8C\u6210\uFF01\u62A5\u544A\u5DF2\u751F\u6210\u3002");
    const leaf = this.app.workspace.getLeaf(false);
    const reportFileObj = this.app.vault.getAbstractFileByPath(reportPath);
    if (leaf && reportFileObj instanceof import_obsidian3.TFile)
      await leaf.openFile(reportFileObj);
  }
};
var QueryModal = class extends import_obsidian3.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u{1F50D} \u667A\u80FD Wiki \u95EE\u7B54\u68C0\u7D22" });
    const inputEl = contentEl.createEl("input", {
      type: "text",
      placeholder: "\u8BF7\u8F93\u5165\u60A8\u5BF9 Wiki \u7684\u7591\u95EE\uFF08\u652F\u6301\u6A21\u7CCA\u8BED\u4E49\u68C0\u7D22\uFF09..."
    });
    inputEl.addClass("genwiki-query-input");
    const submitBtn = contentEl.createEl("button", { text: "\u63D0\u4EA4\u95EE\u7B54" });
    const resultContainer = contentEl.createDiv({ cls: "genwiki-query-result" });
    submitBtn.addEventListener("click", async () => {
      const query = inputEl.value.trim();
      if (!query)
        return;
      resultContainer.setText("\u6B63\u5728\u5206\u6790\u68C0\u7D22\uFF0C\u8BF7\u7A0D\u5019...");
      submitBtn.disabled = true;
      try {
        const ans = await this.plugin.executeQuery(query);
        resultContainer.empty();
        const preEl = resultContainer.createEl("pre", { cls: "genwiki-query-pre" });
        preEl.setText(ans);
      } catch (e) {
        resultContainer.setText(`\u67E5\u8BE2\u9519\u8BEF: ${e.message}`);
        console.error(e);
      } finally {
        submitBtn.disabled = false;
      }
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var GenWikiSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  addModelSetting(containerEl, providerName, presetsModel, currentModel, onModelChange) {
    const isPreset = presetsModel.includes(currentModel);
    const dropdownValue = isPreset ? currentModel : "customized";
    new import_obsidian3.Setting(containerEl).setName(`${providerName} Model`).setDesc("\u9009\u62E9\u9884\u8BBE\u6A21\u578B\u6216\u81EA\u5B9A\u4E49").addDropdown((dropdown) => {
      for (const m of presetsModel) {
        dropdown.addOption(m, m);
      }
      dropdown.addOption("customized", "\u81EA\u5B9A\u4E49 (Custom)");
      dropdown.setValue(dropdownValue);
      dropdown.onChange(async (val) => {
        if (val === "customized") {
          await onModelChange("");
        } else {
          await onModelChange(val);
        }
        this.display();
      });
    });
    if (dropdownValue === "customized") {
      new import_obsidian3.Setting(containerEl).setName(`\u81EA\u5B9A\u4E49 ${providerName} Model ID`).setDesc("\u8BF7\u8F93\u5165\u60A8\u60F3\u8981\u4F7F\u7528\u7684\u81EA\u5B9A\u4E49\u6A21\u578B\u6807\u8BC6\u7B26").addText(
        (text) => text.setPlaceholder("\u4F8B\u5982: gpt-4-custom").setValue(currentModel).onChange(async (val) => {
          await onModelChange(val);
        })
      );
    }
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("\u5927\u6A21\u578B\u8BBE\u7F6E").setHeading();
    new import_obsidian3.Setting(containerEl).setName("\u9ED8\u8BA4\u5927\u6A21\u578B\u4F9B\u5E94\u5546 (Provider)").setDesc("\u9009\u62E9\u4F7F\u7528\u7684\u6A21\u578B\u901A\u9053").addDropdown((dropdown) => dropdown.addOption("gemini", "Google Gemini").addOption("anthropic", "Anthropic Claude").addOption("openai", "OpenAI").addOption("deepseek", "DeepSeek").addOption("kimi", "Moonshot Kimi").addOption("openrouter", "OpenRouter").setValue(this.plugin.settings.provider).onChange(async (value) => {
      this.plugin.settings.provider = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    const prov = this.plugin.settings.provider;
    if (prov === "gemini") {
      new import_obsidian3.Setting(containerEl).setName("Gemini API Key").addText((text) => text.setPlaceholder("Enter Gemini API Key").setValue(this.plugin.settings.geminiApiKey).onChange(async (value) => {
        this.plugin.settings.geminiApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "Gemini",
        [
          "gemini-3.5-flash",
          "gemini-3.1-pro-preview",
          "gemini-3.1-flash-lite",
          "gemini-2.5-pro",
          "gemini-2.5-flash",
          "gemini-2.5-flash-lite",
          "gemini-flash-latest"
        ],
        this.plugin.settings.geminiModel,
        async (val) => {
          this.plugin.settings.geminiModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "anthropic") {
      new import_obsidian3.Setting(containerEl).setName("Anthropic API Key").addText((text) => text.setPlaceholder("Enter Anthropic API Key").setValue(this.plugin.settings.anthropicApiKey).onChange(async (value) => {
        this.plugin.settings.anthropicApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "Anthropic",
        [
          "claude-opus-4-8",
          "claude-sonnet-4-6",
          "claude-haiku-4-5",
          "claude-haiku-4-5-20251001"
        ],
        this.plugin.settings.anthropicModel,
        async (val) => {
          this.plugin.settings.anthropicModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "openai") {
      new import_obsidian3.Setting(containerEl).setName("OpenAI API Key").addText((text) => text.setPlaceholder("Enter OpenAI API Key").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
        this.plugin.settings.openaiApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "OpenAI",
        [
          "gpt-5.5",
          "gpt-5.5-pro",
          "gpt-5.4",
          "gpt-5.4-mini",
          "gpt-5.4-nano",
          "chat-latest"
        ],
        this.plugin.settings.openaiModel,
        async (val) => {
          this.plugin.settings.openaiModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "deepseek") {
      new import_obsidian3.Setting(containerEl).setName("DeepSeek API Key").addText((text) => text.setPlaceholder("Enter DeepSeek API Key").setValue(this.plugin.settings.deepseekApiKey).onChange(async (value) => {
        this.plugin.settings.deepseekApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "DeepSeek",
        [
          "deepseek-v4-pro",
          "deepseek-v4-flash",
          "deepseek-chat",
          "deepseek-reasoner"
        ],
        this.plugin.settings.deepseekModel,
        async (val) => {
          this.plugin.settings.deepseekModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "kimi") {
      new import_obsidian3.Setting(containerEl).setName("Kimi API Key").addText((text) => text.setPlaceholder("Enter Moonshot API Key").setValue(this.plugin.settings.kimiApiKey).onChange(async (value) => {
        this.plugin.settings.kimiApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "Kimi",
        [
          "kimi-k2.6",
          "kimi-k2.5",
          "moonshot-v1-8k",
          "moonshot-v1-32k",
          "moonshot-v1-128k",
          "moonshot-v1-8k-vision-preview",
          "moonshot-v1-32k-vision-preview",
          "moonshot-v1-128k-vision-preview"
        ],
        this.plugin.settings.kimiModel,
        async (val) => {
          this.plugin.settings.kimiModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    if (prov === "openrouter") {
      new import_obsidian3.Setting(containerEl).setName("OpenRouter API Key").addText((text) => text.setPlaceholder("Enter OpenRouter API Key").setValue(this.plugin.settings.openrouterApiKey).onChange(async (value) => {
        this.plugin.settings.openrouterApiKey = value;
        await this.plugin.saveSettings();
      }));
      this.addModelSetting(
        containerEl,
        "OpenRouter",
        [
          "openai/gpt-5.5",
          "openai/gpt-5.5-pro",
          "openai/gpt-chat-latest",
          "anthropic/claude-opus-4.8",
          "anthropic/claude-sonnet-4.6",
          "anthropic/claude-sonnet-4.5",
          "google/gemini-3.5-flash",
          "google/gemini-3.1-flash-lite",
          "google/gemini-3.1-pro-preview",
          "deepseek/deepseek-v4-pro",
          "deepseek/deepseek-v4-flash",
          "moonshotai/kimi-k2.6",
          "moonshotai/kimi-k2.6:free",
          "qwen/qwen3.7-max",
          "qwen/qwen3.7-plus",
          "x-ai/grok-4.3",
          "mistralai/mistral-medium-3-5",
          "openrouter/free"
        ],
        this.plugin.settings.openrouterModel,
        async (val) => {
          this.plugin.settings.openrouterModel = val;
          await this.plugin.saveSettings();
        }
      );
    }
    new import_obsidian3.Setting(containerEl).setName("\u76EE\u5F55\u8DEF\u5F84\u914D\u7F6E (Paths)").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Clippings \u76EE\u5F55").setDesc("\u7F51\u9875\u526A\u85CF\u5B58\u653E\u8DEF\u5F84").addText((text) => text.setValue(this.plugin.settings.clippingsDir).onChange(async (value) => {
      this.plugin.settings.clippingsDir = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian3.Setting(containerEl).setName("Wiki \u76EE\u5F55").setDesc("\u7ED3\u6784\u5316\u77E5\u8BC6\u6587\u4EF6\u5B58\u653E\u8DEF\u5F84").addText((text) => text.setValue(this.plugin.settings.wikiDir).onChange(async (value) => {
      this.plugin.settings.wikiDir = value;
      await this.plugin.saveSettings();
    }));
  }
  getSettingDefinitions() {
    return [];
  }
};
